- ChangeLog_branch
- src/biogeophys/InfiltrationExcessRunoffMod.F90
- src/biogeophys/SaturatedExcessRunoffMod.F90
**NOTE: This PR was originally created in the temporary CTSM repository, Sep 13, 2017. I am moving over most of the comments from there: both my own and those of @martynpclark .**
**Here was the original comment:**
Martyn Clark reviewed the VIC implementation, and felt that the current
implementation of infiltration excess runoff is inconsistent with the
standard VIC implementation. It appears that what was being called VIC's
infiltration excess runoff was actually just an attempt to give a better
numerical approximation to the solution for saturated surface excess
runoff. So deleting this leaves only a first-order approximation to
VIC's saturated surface excess runoff.
Eventually we may want to put in place a more accurate solution for
VIC's saturated surface excess runoff. But Martyn's …
> Remove infiltration excess runoff for VIC

- .config_files.xml
- .gitignore
- CESM.cfg
- cime_config/buildcpp
- cime_config/buildlib
- cime_config/buildnml
- src/CMakeLists.txt
Note that the cism version is based off of cism2_1_44, rather than the
previously-pointed-to cism2_1_40
> Point to a git version of cism and get standalone build to work

- bld/CLMBuildNamelist.pm
- bld/configure
- cime_config/buildcpp
- cime_config/buildnml
This is needed to support a standalone checkout, where cime appears in a
different location relative to the bld directory
> Use cimeroot rather than hard-coded relative path

- Externals.cfg
- cime_config/testdefs/ExpectedTestFails.xml
- doc/ChangeLog
- doc/ChangeSum
This cime tag auto-detects model=cesm based on the presence of
manage_externals
The diffs in this cime tag are simply:
```diff
diff --git a/scripts/lib/CIME/utils.py b/scripts/lib/CIME/utils.py
index 803ac9695..a41656619 100644
--- a/scripts/lib/CIME/utils.py
+++ b/scripts/lib/CIME/utils.py
@@ -171,7 +171,8 @@ def get_model():
if (model is None):
srcroot = os.path.dirname(os.path.abspath(get_cime_root()))
-        if os.path.isfile(os.path.join(srcroot, "SVN_EXTERNAL_DIRECTORIES")):
+        if os.path.isfile(os.path.join(srcroot, "SVN_EXTERNAL_DIRECTORIES")) \
+           or os.path.isdir(os.path.join(srcroot, "manage_externals")):
model = 'cesm'
else:
model = 'acme'
```
These changes are already on cime master (made by @jedwards4b ); here I have cherry-picked them onto the cime branch …
> Point to a new cime tag

- README.rst
I think the "Getting started with ctsm in git" page is more relevant for
most people, so I'm putting that one first.
> Reorder links

- .gitignore
- Externals_CLM.cfg
Bring in a version of PTCLMmkdata that works in the new CTSM git checkout directory structure.
> Bring in a working PTCLMmkdata version

- Externals.cfg
- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/DaylengthMod.F90
- src/biogeophys/test/Daylength_test/CMakeLists.txt
- src/biogeophys/test/Daylength_test/test_compute_max_daylength.pf
- src/main/clm_driver.F90
- src/main/clm_initializeMod.F90
This is needed for max day length to remain correct with time-varying
orbital parameters, which in turn is needed to achieve exact restart
in a run that crosses the year boundary with time-varying orbital
parameters.
Fixes #379
Fixes #260
> Update max day length (max_dayl) each time step

- src/main/histFileMod.F90
- src/utils/clmfates_interfaceMod.F90
New dimensions for FATES history output: height, age*pft, size*age*pft.  corresponds to the set of changes in https://github.com/NGEET/fates-clm/pull/30, which align with FATES changes in https://github.com/NGEET/fates/pull/316.
I haven't tested these yet in CTSM; @rgknox could you put through your new FATES-CTSM test regime?
> Fates history dimensions: height, age*pft, size*age*pft

- src/main/controlMod.F90
- src/main/histFileMod.F90
The current CTSM forces the default one monthly time point per file for the first history tape, even if the user specifies otherwise.  This was pointed out in issue #85 and separately rediscovered at least one other time by me.  This code fixes that and allows the user-specified value of hist_mfilt to occur.  Code change here is based on https://github.com/ESCOMP/ctsm/issues/85#issuecomment-352209370 from @ekluzek.  I confirm that the change does allow specifying other than one time step per file.
> Allow first history tape to have other than one time point per file

- .github/PULL_REQUEST_TEMPLATE.md
Make PR template questions less prominent
I find that, with these big, bold headings, my eye is drawn to the
headings and it's hard to read the important text that the user has
entered him/herself. I find that having the questions in normal text
makes a filled-out PR easier to read.
> Make PR template questions less prominent

- doc/.ChangeLog_template
It no longer will work to denote these changes via a tag numbering
convention, so Dave, Erik and I decided that we should call this out in
the ChangeLog.
> ChangeLog: ask about significant changes to various configurations

- .gitignore
- bld/namelist_files/use_cases/1850_control.xml
- src/biogeochem/CNVegCarbonFluxType.F90
- src/biogeochem/CNVegNitrogenFluxType.F90
- src/soilbiogeochem/SoilBiogeochemNitrogenFluxType.F90
- test/tools/README
- test/tools/TCBCFGtools.sh
- test/tools/input_tests_master
- test/tools/test_driver.sh
- tools/mkprocdata_map/src/Makefile.common
- tools/mksurfdata_map/Makefile.data
- tools/mksurfdata_map/src/Makefile.common
- tools/mksurfdata_map/src/mkpctPftTypeMod.F90
- tools/mksurfdata_map/src/mkpftMod.F90
- tools/mksurfdata_map/src/mksurfdat.F90
Addresses issue #426 where special land units were assigned spval in InitCold for FUN variables.  As @billsacks noted in #431 "BGC variables are all set to 0 for special landunits via the SetValues subroutines in each *Type.F90 module". 
With missing values (instead of zeros), grid cell averaging did not work correctly, initially noticed over lakes where NFIX (patch level variable) > NFIX_TO_SMINN (the column level total).  PFT level output (h1) for NFIX matched grid cell totals (h0) for NFIX_TO_SMINN.
Most changes in CNVegNitrogenFluxType.F90 including:
* Set these FUN variables to 0 for special land units. (This may be rudundant?)
* Reset spval to 0 in the Restart subroutine, to overwrite existing restart files.
Similar, but less extensive modifications need for CNVegCarbonFluxType.F90 …
> Addresses bugs with gridcell averaging of FUN variables

- src/utils/clmfates_interfaceMod.F90
This PR ensures that when FATES passes back area weights to CTSM, the bare-soil patch is not given a negative area.  The precisions on our patch area calculations can stray up to 1e-12, which is small but had made it possible that an nearly-zero negative bare-soil patch area was possible.  This fix simply bounds it at 0.
> Protected fates calculation of bare-soil area to not go below 0

- cime_config/testdefs/testmods_dirs/clm/decStart/shell_commands
Add missing --append flag to decStart xmlchange command
Fixes #424 
Answers will change for some tests: decStart and ciso_decStart
Testing performed:
Tested creation of `ERP_D.f10_f10_musgs.IHistClm50Bgc.roo2_gnu.clm-decStart`
> Add missing --append flag to decStart xmlchange command

- bld/namelist_files/namelist_defaults_clm4_5.xml
This PR accompanies https://github.com/NGEET/fates/pull/402 by updating the default fates parameter file for testing.
Are answers expected to change (and if so in what way)? no from CTSM side.
Any User Interface Changes (namelist or namelist defaults changes)?  updated parameter default file.
(aux_clm on cheyenne for gnu/pgi and hobart for gnu/pgi/nag is the standard for tags on master)
cheyenne, fates, intel,  all PASS
**NOTE: Be sure to …
> Update fates default parameter file

- bld/namelist_files/namelist_defaults_clm4_5.xml
- bld/namelist_files/use_cases/1850_control.xml
- bld/namelist_files/use_cases/20thC_transient.xml
- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
- doc/ChangeLog
- doc/ChangeSum
Update to use of new 1850 Nitrogen-deposition file as well as correcting year_last for some of the CLM streams. These are the changes that went into release-clm5.0.05 being moved to master.
CTSM Issues Fixed (include github issue #): #461
Are answers expected to change (and if so in what way)? Yes!
For 1850 cases with BGC on
And for post 2005 for IHist cases.
Testing performed, if any: testing was done on the release branch
Will be repeated here before this comes to master.
> Move changes from release-clm5.0.05 onto master

- bld/namelist_files/namelist_defaults_clm4_5.xml
This updates the default path to the FATES default parameter file. This file has been updated to reflect changes in https://github.com/NGEET/fates/pull/414.
See https://github.com/NGEET/fates/pull/414
Are answers expected to change (and if so in what way)?  This change, synced with https://github.com/NGEET/fates/pull/414, should produce nigh-indistinguishable, yet not B4B results with fates_next_api and FATES/master.
Any User Interface Changes (namelist or namelist defaults changes)? No namelist changes, updates to default fates_parameter file only.
See https://github.com/NGEET/fates/pull/414 for in depth comparison.  The default file pull was tested on Cheyenne using …
> Updating default FATES parameter file

- Externals_CLM.cfg
- bld/namelist_files/namelist_defaults_clm4_5.xml
This updates the path to the default parameter file for FATES.  This file matches new specifications designed in https://github.com/NGEET/fates/pull/418.
Answers should change in FATES only, and they should only be of scales associated with rounding errors or order of operations.
New parameter file.
(aux_clm on cheyenne for …
> Updated path to fates default parameter file

- bld/namelist_files/createMkSrfEntry.py
- bld/namelist_files/namelist_defaults_clm4_5_tools.xml
- bld/namelist_files/namelist_definition_clm4_5.xml
- test/tools/README.testnames
- test/tools/input_tests_master
- test/tools/nl_files/mksrfdt_1x1_numaIA_crp_SSP5-8.5_1850-2100
- test/tools/tests_posttag_nompi_regression
- test/tools/tests_pretag_cheyenne_nompi
- tools/mksurfdata_map/mksurfdata.pl
Add in ability of mksurfdata_map to handle CMIP6 future scenarios with -ssp_rcp option removing the -rcp option for CMIP5 future scenarios. Also add the SSP5-8.5 future scenario rawfiles into the XML database for tools.
Also added a script that can create the XML for each year for the rawdata PFT files.
Contributors other than yourself, if any: rawdata from @lawrencepj1 
Are answers expected to change (and if so in what way)? CTSM code is identical, mksurfdata_map will give same results for old data, just new capability for new data.
Any User Interface Changes (namelist or namelist defaults changes)? mksurfdata.pl
Command line option for mksurfdata.pl changed from -rcp to -ssp_rcp
Testing performed, if any: Ran mksurfdata.pl for f09 SSP5-8.5 …
> Add in ability for mksurfdata_map to handle ssp_rcp scenarios and specifically SSP5-8.5

- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_definition_clm4_5.xml
- bld/unit_testers/build-namelist_test.pl
- doc/ChangeLog
- doc/ChangeSum
- src/dyn_subgrid/dynSubgridControlMod.F90
- src/dyn_subgrid/dyncropFileMod.F90
Corrects the baseline for transient crops in transient pft runs
#538 
Yes, in transient pft runs
Ran standard intel & gnu test-suites to generate baseline-13 from branch trans_pft_issue538 while comparing to baseline-12. Expect same or similar FAILures as between branch collapse2gencrop & baseline-12:
Gnu generated same DIFF FAILures + 2 new TPUTCOMP FAILures
Intel generated same DIFF FAILures, except 1 new RUN FAILure: corrected, retested, and now it’s among same DIFF FAILures
Ran same tests bet. branch collapse2gencrop & baseline-13 hoping for no …
> Transient pft issue #538

- cime_config/usermods_dirs/carbon_isotopes/user_nl_clm
- cime_config/usermods_dirs/cmip6/include_user_mods
User-mod directory for carbon_isotopes and include it for the cmip6 user-mod
Add carbon_isotopes user-mod directory to turn on c13 and c14 carbon isotopes.
Yes, just for the cmip6 user-mod test cases
Any User Interface Changes (namelist or namelist defaults changes)? Changes cmip6
Testing performed, if any: none yet
(aux_clm on cheyenne for gnu/pgi and hobart for gnu/pgi/nag is the standard for tags on master)
> Add carbon_isotope user-mod directory to turn on c13 and c14

- cime_config/config_component.xml
This was suggested by @rljacob and supported by @mvertens @jedwards4b
and @bertinia as a mechanism to provide CMIP6-specific compsets.
This allows us to have a compset like this:
```xml
<compset>
<alias>B1850CMIP6</alias>
<lname>1850_CAM60_CLM50%BGC-CROP%CMIP6DECK_CICE_POP2%ECO%ABIO-DIC_MOSART_CISM2%NOEVOLVE_WW3_BGC%BDRD</lname>
<science_support grid="f09_g17_gl4"/>
<science_support grid="f09_g17"/>
</compset>
```
I have tentatively chosen the modifier %CMIP6DECK rather than just
%CMIP6, mainly because I imagine we might want some other %CMIP6XXX
modifiers later, and if we had a simple %CMIP6 modifier, it would be
harder to write a correct regular expression that matches %CMIP6XXX
without accidentally matching %CMIP6. For CTSM, my impression is that we
want the same mods for all DECK …
> Support a %CMIP6DECK compset modifier

- src/utils/clmfates_interfaceMod.F90
In PR https://github.com/NGEET/fates/pull/428, we refactor fates restarts so that we don't need to save some massive restart variables.  However, we do need to initiate a call early in the restart process that will re-create these arrays (radiation absorbtion fractions).  However, we can't re-use any existing calls through the interface.  
Fates issue: https://github.com/NGEET/fates/issues/12
hard to say, results should be nigh b4b, but the order of operations will change slightly, so I'm expecting very small round-off errors, but possibly not...
no
(List …
> fates refactor of 3d arrays in restart - api changes

- Externals.cfg
- bld/namelist_files/namelist_defaults_clm4_5.xml
- doc/ChangeSum
- doc/release-clm5.0.ChangeLog
Fix a bug in the XML for finding the surface dataset for f05 at 1850 and non-crop. Also update to latest cesm2.1.0 version of cime. This fix important for SDYN mode in CAM.
CTSM Issues Fixed (include github issue #): #576
Standard aux_clm testing on cheyenne and hobart, all PASS as expected...
> Fix bug in XML for surface dataset for f05 1850 non-crop

- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/CMakeLists.txt
- src/biogeophys/HydrologyNoDrainageMod.F90
- src/biogeophys/IrrigationMod.F90
- src/biogeophys/SoilHydrologyMod.F90
- src/biogeophys/WaterDiagnosticBulkType.F90
- src/biogeophys/WaterFluxType.F90
- src/biogeophys/test/Irrigation_test/README
- src/biogeophys/test/Irrigation_test/test_irrigation.pf
- src/main/clm_driver.F90
- src/unit_test_shr/unittestSimpleSubgridSetupsMod.F90
- src/unit_test_shr/unittestWaterTypeFactory.F90
Set tracer version of irrigation fluxes.
This required a substantial rewrite of ApplyIrrigation (now renamed to
CalcIrrigationFluxes). The problem was that the code was written to
compute the total irrigation withdrawal from groundwater, then use this
to compute the application fluxes (drip/sprinkler), then later divide
this total withdrawal by layer. But for tracer fluxes to be computed
correctly, we needed to reorder this, so that the per-layer withdrawals
are determined before determining the application fluxes. This is
because the application flux needs to know the tracer concentrations of
the source, which requires knowing which layers the source is drawing
from. This was made more challenging because of the mix of patch-level
and column-level variables at play: irrigation demand is …
> Set tracer version of Irrigation fluxes

- bld/namelist_files/namelist_defaults_clm4_5.xml
- src/biogeophys/SurfaceRadiationMod.F90
- src/utils/clmfates_interfaceMod.F90
- src/utils/clmfates_paraminterfaceMod.F90
Simple changes that update DEBUG logicals to lowercase.  I believe this has already been done in master, but we are encouring users to update CIME, so these changes need to be in fates_next_api.
Synced with: https://github.com/NGEET/fates/pull/431
no
/gpfs/fs1/scratch/rgknox/clmed-tests/fates.cheyenne.intel.height-sorting-ranked-v3-C5dc7f0a-F3ae7ce5
(hash CLM: 5dc7f0a) I had not yet committed the changes while running this test, so the hash is the head of fates_next_api.h
Also: 
/glade/scratch/rgknox/clmed-tests/fates.cheyenne.intel.fire-mortality-diagnosti …
> Changed DEBUG to debug to be compatible with new CIME

- .gitignore
- Externals.cfg
- bld/CLMBuildNamelist.pm
- bld/namelist_files/createMkSrfEntry.py
- bld/namelist_files/namelist_defaults_clm4_5.xml
- bld/namelist_files/namelist_defaults_clm4_5_tools.xml
- bld/namelist_files/namelist_definition_clm4_0.xml
- bld/namelist_files/namelist_definition_clm4_5.xml
- bld/unit_testers/build-namelist_test.pl
- cime_config/testdefs/testmods_dirs/clm/DA_multidrv/user_nl_clm_0001
- cime_config/testdefs/testmods_dirs/clm/DA_multidrv/user_nl_clm_0002
- doc/ChangeSum
- doc/release-clm5.0.ChangeLog
- src/biogeochem/CNBalanceCheckMod.F90
- src/biogeochem/CNCStateUpdate1Mod.F90
- src/biogeochem/CNDriverMod.F90
- src/biogeochem/CNVegCarbonFluxType.F90
- src/biogeochem/CNVegCarbonStateType.F90
- src/biogeochem/CNVegetationFacade.F90
- src/biogeochem/EDBGCDynMod.F90
- tools/mksurfdata_map/Makefile.data
- tools/mksurfdata_map/README.developers
- tools/mksurfdata_map/mksurfdata.pl
- tools/mksurfdata_map/src/mksurfdat.F90
Add an option to dribble the XSMRPOOL at crop harvest to the atmosphere over about a half year.
Contributors other than yourself, if any: @olyson
CTSM Issues Fixed (include github issue #): #590 #589
only when option is invoked
New option: dribble_crophrv_xsmrpool_2atm
Also don't give contents of lai_stream namelist unless use_lai_streams is on.
Testing performed, if any: Ran a few tests by hand to show answers don't change when option off
and answers do when turned on. Also compared to make sure @olyson case clm50_release-clm5.0.15_hrv_xsmrpool_to_atm_1deg_GSWP3V1_hist was exact with the option turned on.
@billsacks it's not critical for you to review this. But, …
> Add option to dribble XSMRPOOL at crop harvest to atmosphere over a half year

- src/utils/array_utils.F90.in
- src/utils/test/CMakeLists.txt
- src/utils/test/array_utils_test/CMakeLists.txt
- src/utils/test/array_utils_test/test_find_k_max_indices.pf
Add routine to find indices of max k values in data
This could be useful for ESCOMP/ctsm#457
Just ran unit tests
> Add routine to find indices of max k values in data

- bld/namelist_files/namelist_defaults_clm4_5.xml
This changeset updates the default fates parameter file for testing.  Changes since last change are most notably, the addition of the leaf age dimension.  This is a minor API compatibility change.
See corresponding NGEET/fates PR: https://github.com/NGEET/fates/pull/462
@xuchongang
FATES simulations are expected to have small differences because of subtle changes in the default parameter configuration. FATES is also expected to have roundoff/machine-precision differences when parameters are kept the same because of changes in order of operations.
(List …
> update default fates parameter file

- cime_config/testdefs/testlist_clm.xml
- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/SoilHydrologyInitTimeConstMod.F90
- src/biogeophys/SoilHydrologyType.F90
- src/main/clm_instMod.F90
Initalization of time-varying `zwt`, `zwt_perched`, and `frost_table`  are moved to `InitCold` in `SoilHydrologyType`.
Previously, `zwt`, `zwt_perched`, and `frost_table` were initialized in `SoilHydrologyInitTimeConstMod`.
Contributors other than yourself, if any: Bill Sacks
CTSM Issues Fixed (include github issue #): Fixes  #575
Are answers expected to change (and if so in what way)? No. 
Any User Interface Changes (namelist or namelist defaults changes)? None.
Ran full `aux_clm` test suite and `clm_short` on cheyenne. Not tested on Hobart.
> Soil hydrology initialization of time-constant variables moved to SoilHydrologyType.

- Externals.cfg
- doc/ChangeSum
- doc/release-clm5.0.ChangeLog
Update cime to a version that works on cheyenne after the Mar/5th/2019 downtime that caused problems with using mpt/2.16.
CTSM Issues Fixed (include github issue #): #655 #654
Are answers expected to change (and if so in what way)? Yes (only at f19_g17 resolution)
Any User Interface Changes (namelist or namelist defaults changes)? none
Ran standard testing on hobart, and cheyenne
Ran tools testing on hobart and cheyenne
> Update to cime version that works on cheyenne after the mar/5th/2019 downtime

- src/biogeophys/WaterfluxType.F90
QSNOEVAP for history was pointing to the wrong internal variable. This corrects it to point to the correct one.
Contributors other than yourself, if any: @olyson 
CTSM Issues Fixed (include github issue #): #624
Are answers expected to change (and if so in what way)? Yes (just for QSNOEVAP)
Ran SMS_Lm1_D.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-output_crop_highfreq
and made sure only the QSNOEVAP variable changed on history
> Qsnoevapfix

- Externals.cfg
- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/namelist_files/namelist_definition_ctsm.xml
- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testmods_dirs/clm/glcMEC_decrease/README
- cime_config/testdefs/testmods_dirs/clm/glcMEC_decrease/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/glcMEC_increase/README
- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/BalanceCheckMod.F90
- src/biogeophys/HydrologyDrainageMod.F90
- src/biogeophys/LakeHydrologyMod.F90
- src/biogeophys/TemperatureType.F90
- src/biogeophys/TotalWaterAndHeatMod.F90
- src/biogeophys/WaterStateType.F90
- src/dyn_subgrid/CMakeLists.txt
- src/dyn_subgrid/dynConsBiogeophysMod.F90
- src/dyn_subgrid/dynSubgridControlMod.F90
- src/dyn_subgrid/test/CMakeLists.txt
- src/dyn_subgrid/test/dynConsBiogeophys_test/CMakeLists.txt
- src/dyn_subgrid/test/dynConsBiogeophys_test/test_dyn_cons_biogeophys.pf
- src/main/clm_initializeMod.F90
- src/main/subgridAveMod.F90
- src/unit_test_shr/unittestWaterTypeFactory.F90
Subtract virtual states to reduce dynbal fluxes for transient glaciers
Up until now, when computing the dynbal correction fluxes for transient
glacier columns, we have been (1) counting the mass and energy in the
ice column as if that is a real state, but on the other hand (2) NOT
accounting for the fact that glacier columns don't represent the soil
under glacier. These two issues work in opposite directions, but (1)
dominates, because there is much more ice (and energy, I think) in the
roughly 50 m of glacial ice than there is in a typical 50 m soil
column.
In discussing this issue with @whlipscomb, we came up with the idea of
subtracting some baseline value from each glacier column. I think that,
as long as we subtract the same baseline value throughout an entire
simulation for a given …
> Reduce dynbal fluxes with dynamic glaciers

- doc/ChangeLog
- doc/ChangeSum
- python/ctsm/run_sys_tests.py
- python/ctsm/test/test_machine.py
- python/ctsm/test/test_run_sys_tests.py
- src/biogeophys/BalanceCheckMod.F90
Up until now, the BalanceCheckMod code in biogeophysics did not check all the possible errors over all columns or patches with the error threshold for aborting clm and it merely compared the last column/patch found (where warning threshold is met) with the error threshold. Therefore, there was always a possibility that the abort is not triggered when it should have been. @lvankampenhout and @billsacks pointed out this issue (Issue #55) for soil energy balance check. A similar issue is also happening for the other balance checks in `BalanceCheckMod.F90`. 
Below is the list of the balance checks with a similar issue:
1. Water balance check
2. Snow balance check
3. Solar radiation energy balance check
4. Longwave radiation energy balance check
5. Surface energy balance check
6. Soil energy …
> Fixing the balance check to check for possible errors in all columns/patches

- src/biogeophys/CanopyFluxesMod.F90
- src/biogeophys/CanopyHydrologyMod.F90
- src/biogeophys/TotalWaterAndHeatMod.F90
This PR is the first step towards cleaning up the relationship between h2ocan, liqcan and snocan. This replaces uses of `h2ocan_patch(p)` with `(liqcan_patch(p) + snocan_patch(p))`, generally via a temporary variable, `h2ocan_new = liqcan_patch(p) + snocan_patch(p)`. In each part of the code where I have made this replacement, I have put in temporary checks to ensure that these two values of h2ocan (`h2ocan_patch(p) vs. liqcan_patch(p)+snocan_patch(p)`) are the same within roundoff. I have run the full aux_clm test suite on these changes to ensure that the two expressions are always the same within roundoff.
This does change answers, because in general, h2ocan_patch differs at the roundoff level from liqcan_patch+snocan_patch. These roundoff-level differences can lead to divergent code …
> Replace h2ocan with liqcan+snocan: First stage

- python/ctsm/joblauncher/job_launcher_qsub.py
Without this, we run into the issue noted in
https://github.com/ESCOMP/ctsm/issues/692. This fixes the problem. I
don't fully understand the need for this, but from reading some stack
overflow posts, I'm not surprised that we need this.
Resolves ESCOMP/ctsm#692
Manual testing of #692 issue. Also ran run_sys_tests with python2 loaded on cheyenne.
Also, from python directory: make python=python2 test, make python=python3 test, make lint
> Use universal_newlines in call to subprocess.Popen

- Externals.cfg
- bld/namelist_files/checkmapfiles.ncl
- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/namelist_files/namelist_defaults_ctsm_tools.xml
- bld/namelist_files/namelist_defaults_overall.xml
- bld/namelist_files/namelist_definition_ctsm.xml
- cime_config/config_pes.xml
- python/README.md
- tools/README
- tools/mkmapdata/README
- tools/mkmapdata/mkmapdata.sh
- tools/mksurfdata_map/Makefile.data
Add support for NLDAS grid
Contributors other than yourself, if any: @barlage helped with some file creation
Any User Interface Changes (namelist or namelist defaults changes)? none
SMS_D.nldas2_mnldas2.I2000Clm50SpGs.cheyenne_intel.clm-default
> Nldas grid

- src/biogeophys/CanopyHydrologyMod.F90
Previously: if it was above freezing, snow was allowed to accumulate
beyond the specified capacity, and if it was below freezing, liquid was
allowed to accumulate beyond the specified capacity. Sean Swenson, Keith
Oleson and Dave Lawrence agreed that this seems wrong.
This commit changes the behavior so that both liquid and snow canopy
capacities are enforced regardless of temperature.
- Change supported by @swensosc @olyson @dlawrenncar 
Resolves ESCOMP/ctsm#699
Are answers expected to change (and if so in what way)? YES
We expect answer changes, though probably fairly small. @olyson will investigate this after it comes to master. …
> Remove excess canopy liquid/snow regardless of temperature

- Externals.cfg
- bld/namelist_files/namelist_defaults_clm4_5.xml
- bld/namelist_files/namelist_defaults_clm4_5_tools.xml
- bld/unit_testers/build-namelist_test.pl
- cime_config/config_component.xml
- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
- doc/.ChangeLog_template
- doc/.release-ChangeLog_template
- doc/ChangeSum
- doc/release-clm5.0.ChangeLog
- tools/ncl_scripts/getco2_historical.ncl
With updated cime with CO2 and prescribed aerosol files in place.
Fixes #711
Fixes #708
Fixes #707
Fixes #712 
Are answers expected to change (and if so in what way)? Yes (just for SSP and present day compsets)
Any User Interface Changes (namelist or namelist defaults changes)? Yes
New CO2 SSP files and three SSP presaero files in place (SSP5-8.5, SSP2-4.5, SSP3-7.0)
won't run for other cases, because of missing presaero files
Also remove the ndep files that aren't in place (ndep files in place are: SSP1-2.6, SSP5-8.5, SSP2-4.5, SSP3-7.0)
Will now abort on the other SSP's since the files aren't in place
Testing performed, if any: Ran ISSP compsets
These work: …
> Fix a few issues, and update cime to a version with CO2 SSP files as well as three presaero SSP files

- bld/namelist_files/namelist_defaults_ctsm.xml
- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/CanopyHydrologyMod.F90
Rename
dewmx to liq_canopy_storage_scalar
sno_stor_max to sno_canopy_storage_scalar
Change snocanmx, liqcanmx, and fcansno to...
`snocanmx = params_inst%snow_canopy_storage_scalar(p) * (elai(p) + esai(p))`
`liqcanmx = params_inst%liq_canopy_storage_scalar(p) * (elai(p) + esai(p))`
`fcansno(p) = (snocan(p) / (vegt * params_inst%sno_stor_max))**0.15_r8`
@billsacks @swensosc 
fixes #710 
Roundoff
New clm45 and clm50 param files to include the new names
./create_test ERS_D_Ld10.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-rm_indiv_lunits_and_collapse_to …
> Renaming, correcting, simplifying parameters dewmx and sno_stor_max

- bld/namelist_files/namelist_defaults_clm4_5.xml
- doc/ChangeSum
- doc/release-clm5.0.ChangeLog
Update C13 and C14 historical time series files to be in NetCDF-3 classic format rather than NetCDF-4. This is a problem with pnetcdf on certain external machines. "nccopy -k classic file1 file2" was used for the conversion.
Contributors other than yourself, if any: @jedwards4b found the problem
CTSM Issues Fixed (include github issue #): #734 
Any User Interface Changes (namelist or namelist defaults changes)? C13 and C14 historical files pointed to
Testing performed, if any: Running SMS_D_Ly2.1x1_numaIA.IHistClm50BgcCropGs.cheyenne_intel.clm-ciso_bombspike1963
> Convert the file from NetCDF-4 classic format to NetCDF-3 classic format

- Externals_CLM.cfg
- bld/namelist_files/namelist_defaults_clm4_5.xml
This updates the default file and the external pointer to be compatible with fates sci1.27.1_api7.3.0.
Note, this is only a "minor" API change, which I use to flag changes in input file structure (ie parameter file variable names and definitions have changed).  The software interface between the models has not changed.
(aux_clm on cheyenne for gnu/pgi and hobart for gnu/pgi/nag is the standard for tags on master)
see FATES PR 530: https://github.com/NGEET/fates/pull/530
**NOTE: Be sure to check your Coding style against the …
> Fates api 7.3.0

- Externals.cfg
- doc/ChangeLog
- doc/ChangeSum
Update cheyenne to use intel-19 and update mosart to trunk version
Are answers expected to change (and if so in what way)? Yes
All answers will be different on cheyenne with intel compiler
compsets with mosart will change to roundoff due to change in history files
Any User Interface Changes (namelist or namelist defaults changes)? none
Testing performed, if any: regular is running
> Update cheyenne to intel/19 and update mosart

- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/LakeTemperatureMod.F90
As described in the title plus a comment correction.
@billsacks @dlawrenncar 
fixes #760 
Only in diagnostic variable WTGQ
Cheyenne test suite FAILs with DIFFs from dev049 baseline. 
The following commands...
./summarize_cprnc_diffs -basedir /glade/scratch/slevis/tests_0712-173856ch -testid '*'
vi cprnc.summary.\*.by_varname
...confirm that only WTGQ is different from dev049. 
I will repeat on Hobart.
> dz --> dz_lake bug-fix in LakeTemperatureMod.F90 line 960

- doc/ChangeLog
- doc/ChangeSum
- python/ctsm/machine_defaults.py
- src/biogeophys/SoilStateInitTimeConstMod.F90
Previously, on master, there was special-purpose code for the 10SL case
that avoided doing interpolation from the surface dataset to the soil
variables in the model. (In a recent commit, @slevisconsulting changed
the logic to be based on organic_frac_squared, but that dependence was
not correct.) It would be cleaner - especially now that we allow
user-defined soil layer structures - if we could use the general
interpolation code always, rather than sometimes having special-purpose
code that avoids doing the interpolation.
This commit accomplishes that generality. In order to preserve answers
for clm45 cases, I needed to make three changes:
1. The constant 0.025 needed an _r8 appended to it; otherwise, zisoifl
could differ by roundoff from zisoi. I'm confident that this is a
correct fix. …
> Fix interp. of surfdat soil layers so we can use interp. for 10SL case

- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/SoilStateInitTimeConstMod.F90
Referring to 
https://github.com/ESCOMP/ctsm/blob/842185f8ce5da306c7ad1a7955cffca827239c48/src/biogeophys/SoilStateInitTimeConstMod.F90#L398-L404
Changes as recommended by @billsacks in #772:
"... we should be comparing zsoi in the model with zisoi on the file - asking if the node center of a given layer in the model falls in between two interface depths on the file."
Contributors other than yourself, if any: @billsacks
CTSM Issues Fixed (include github issue #): Fixes #772 
Yes. Quoting from #772 "... the vertical interpolation of clay, sand and om_frac from the surface dataset to the model's soil layer structure will sometimes use a different soil layer (off by 1) from what should ideally be used."
Any User Interface Changes …
> Soil texture interpolation bug-fix

- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/namelist_files/use_cases/1850-2100_rcp2.6_transient.xml
- bld/namelist_files/use_cases/1850-2100_rcp4.5_transient.xml
- bld/namelist_files/use_cases/1850-2100_rcp6_transient.xml
- bld/namelist_files/use_cases/1850-2100_rcp8.5_transient.xml
- bld/namelist_files/use_cases/1850_control.xml
- bld/namelist_files/use_cases/2000-2100_rcp8.5_transient.xml
- bld/namelist_files/use_cases/2000_control.xml
- bld/namelist_files/use_cases/20thC_transient.xml
- cime_config/usermods_dirs/output_bgc/user_nl_clm
- doc/ChangeLog
- doc/ChangeSum
- src/biogeochem/CNFireLi2016Mod.F90
- src/biogeochem/CNVegCarbonFluxType.F90
- src/biogeochem/dynConsBiogeochemMod.F90
Fire bug fix and DWT_SLASH change and fix urban stream years for clm4_5.
Contributors other than yourself, if any: @lawrencepj1 @olyson 
CTSM Issues Fixed (include github issue #): #175, #787, #780
fixes #175 urban stream years for clm4_5
fixes #787 DWT_SLASH field
fixes #780 Bug in CN Fire Li 2016 which used latitude in degrees rather than radians
Are answers expected to change (and if so in what way)? Yes
clm5_0 BGC simulations fire ignition changes due to difference in cosine(lat) with
latitude properly in radian's rather than in degrees
A few fields associated with DWT_SLASH change by a small amount due to the averaging
difference for a few cases
Any User Interface Changes (namelist or namelist defaults changes)? N
Testing performed, if any: regular
Running standard testing on …
> Two answer changing fixes (fire, DWT_SLASH) and fix for urban streams for Clm45

- src/main/ncdio_pio.F90.in
remove start and count arguments from 0D variable interface to PIO
This bug shows up when using PIO_VERSION=2 and DEBUG=TRUE
Are answers expected to change (and if so in what way)? NO
Tested with case f19_f19_mg17.I2000Clm50SpGs using both PIO versions and with and without DEBUG=TRUE
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on …
> fix for 0D variable pio interface

- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/WaterDiagnosticBulkType.F90
- src/biogeophys/WaterType.F90
- src/init_interp/initInterp.F90
- src/main/clm_driver.F90
- src/main/clm_initializeMod.F90
- src/main/clm_instMod.F90
- src/main/ncdio_pio.F90.in
- src/main/restFileMod.F90
- src/unit_test_stubs/main/ncdio_pio_fake.F90.in
- src/utils/CMakeLists.txt
- src/utils/IssueFixedMetadataHandler.F90
Due to #783 , frac_sno used to be 0 for all lake points. That was mostly fixed, but the issue is still present on initial conditions files that were generated prior to that fix (which includes most or all of our out-of-the-box restart files). This causes frac_sno to be 0 for lake points at the start of the simulation, even if there is a snow pack present. Currently this doesn't cause significant problems, but I'd like to change the calculation of frac_sno_eff so that it is 0 if frac_sno is 0 - and then this frac_sno problem becomes an issue (causing divide by 0 in at least one place).
I struggled with how to fix this problem. My initial attempts involved setting frac_sno to 1 for lake points that had frac_sno = 0 on the restart file despite having either (attempt 1) snow_depth > 0 or …
> Correct frac_sno = 0 for lakes on old initial conditions files

- bld/namelist_files/namelist_defaults_clm4_5.xml
- bld/namelist_files/use_cases/1850_control.xml
- bld/namelist_files/use_cases/1850_noanthro_control.xml
- bld/namelist_files/use_cases/2000_control.xml
- bld/namelist_files/use_cases/2010_control.xml
- bld/namelist_files/use_cases/20thC_transient.xml
- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testmods_dirs/clm/prescribed/user_nl_clm
- doc/ChangeSum
- doc/release-clm5.0.ChangeLog
- src/biogeophys/SoilMoistureStreamMod.F90
answer changes needed. Move prescribed soil moisture dataset being used.
For soil moisture streams apply over both nat-veg and crop.
This is answer changing.
Point to $CSMDATA/lnd/clm2/prescribed_data/LFMIP-pdLC-SST.H2OSOI.0.9x1.25.20levsoi.natveg.1980-2014.MONS_climo.c190716.nc
CTSM Issues Fixed (include github issue #): #175, #817, #832 #833
Fixes #817 -- Have clm4_5 use the same ndep file as clm5_0 for 1850
Fixes #175 -- Have clm4_5 use the same settings for urbantv years as clm5_0
Fixes #832 -- don't override with missing value, let the model set it
Fixes #833 -- time interpolation of soilm causes bad values for some missing points
Are answers expected to change (and if so in what way)? Yes!
prescribed soil moisture changes, so that grid …
> Some answer changes for release branch

- Externals_CLM.cfg
- bld/namelist_files/namelist_defaults_clm4_5.xml
This PR is synced with https://github.com/NGEET/fates/pull/595
Changes here should only update the default fates parameter file location.
Tag info will be added last in Externals_CLM.cfg after tests pass and FATES side changes are integrated.
See: https://github.com/NGEET/fates/pull/595
Since the parameter files are different, I don't think this will pass b4b tests, even though the values are all the same in the parameter file, and answers should not change.  The parameter names have changed, and new parameter entries have been added that are not used yet.
fates test suite, results TBD
> Updated default fates parameter file for new api 8.1.0 format.

- src/biogeophys/CanopyFluxesMod.F90
- src/utils/clmfates_interfaceMod.F90
During canopy_fluxes(), only patches within the exposed vegetation filter are updated with valid transpiration rates.  We had previously been passing in all values to the fates patches, for use in FATES-HYDRO.  However, this caused fates patches that were not exposed to use uninitialized transpiration rates, instead of zero.  This PR applies a fix so that transpiration is zero in FATES patches by default, and updated only in patches that are in the exposed filter.
This is NOT a backwards incompatible api change, and is NOT synced with a FATES side change. 
https://github.com/NGEET/fates/issues/559
Yes, this may change answers, but only for obscure …
> fixes to transpiration boundary condition to FATES-HYDRO

- doc/ChangeLog
- doc/ChangeSum
- src/main/GetGlobalValuesMod.F90
- src/main/histFileMod.F90
- src/main/subgridRestMod.F90
[E3SM#3163](https://github.com/E3SM-Project/E3SM/pull/3163) makes some changes to speed up restart writes.
As a first step I use E3SM#3163 function GetGlobalIndexArray in place of GetGlobalIndex so as to get global indices by array rather than looping over every element.
@billsacks 
#801 
No.
No.
./create_test ERS_D_Ld6.f10_f10_musgs.I1850Clm45BgcCrop.cheyenne_intel.clm-clm50CMIP6frc -c /glade/p/cgd/tss/ctsm_baselines/ctsm1.0.dev080 -p P93300041 &	**PASS**
> Speed up restart writes

- src/utils/clmfates_interfaceMod.F90
This is a bug fix. The boundary condition to fates for tranpiration flux is only allocated when the hydraulics module is active.  This variable was being zero'd for cases where the array was not allocated.
@serbinsh and  @Qianyuxuan found the error.
FATES issue fixed:  https://github.com/NGEET/fates/issues/605
Are answers expected to change (and if so in what way)?  No, but I don't know how the tests did not catch this!
No
TBD
> FATES: Condition the zeroing of qflx bc_in upon having hydro on

- Externals.cfg
- cime_config/usermods_dirs/_includes/output_base/user_nl_clm
- cime_config/usermods_dirs/_includes/output_base_highfreq/user_nl_clm
- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/BalanceCheckMod.F90
- src/biogeophys/LakeHydrologyMod.F90
- src/biogeophys/SnowHydrologyMod.F90
- src/biogeophys/SoilFluxesMod.F90
- src/biogeophys/SoilHydrologyMod.F90
- src/biogeophys/WaterFluxBulkType.F90
- src/biogeophys/WaterFluxType.F90
- src/main/clm_driver.F90
Resolve [issue#118](https://github.com/ESCOMP/CTSM/issues/118)
I've renamed the variables as discussed in [issue#118](https://github.com/ESCOMP/CTSM/issues/118) throughout the code.
I've also made a couple of minor changes to fix a couple of potential problems with these variables as described in the branch commit logs.
I tested for bfb before changing the history field variables themselves. These changes are all bfb (with the exception of QSNOEVAP) for a 1 month global 2deg simulation, but may not be bfb under all conditions.  QSNOEVAP is not bfb because I've added in qflx_ev_snow for lakes.
Variable names discussed with Bill Sacks, variable functions discussed with Sean Swenson. …
> Resolve Issue#118

- bld/namelist_files/namelist_defaults_ctsm.xml
- cime_config/testdefs/testlist_clm.xml
- doc/ChangeLog
- doc/ChangeSum
- src/biogeochem/CNPrecisionControlMod.F90
- src/biogeochem/DryDepVelocity.F90
- src/main/atm2lndType.F90
- src/main/initVerticalMod.F90
- src/main/subgridRestMod.F90
- src/utils/clmfates_paraminterfaceMod.F90
Resolve issues #683, #874,  #878 , #885, #745 , #838
Fixes #683: writing out FATES parameters only on `masterproc`.
Fixes #874: Changing the number of timesteps to run for `SMS_P720x1_Ln3.hcru_hcru.I2000Clm50BgcCruGs.cheyenne_intel.clm-coldStar`
to prevent failing with CMEPS.
Fixes #878: Removing the unused atm2lnd field. 
Fixes #885: Changing the defaults for `br_root` in `namelist_defaults` to enable FUN with CLM4.5.
Fixes  #745: Removing `ReadNL` private subroutine from `initVerticalMod.F90`.
Fixes #838: Clarifying `ZISNO` in the variable long name.
Contributors other than yourself, if any: @billsacks 
#683, #874,  #878 , #885, #745 , #838 
No.
Any User Interface Changes (namelist or …
> Some BFB Fixes: Resolve issues #683, # 874,  #878, # 885, # 745, #838.

- cime_config/testdefs/testlist_clm.xml
- doc/ChangeLog
- doc/ChangeSum
- src/biogeochem/CNPrecisionControlMod.F90
This PR request resolves issue #811 . 
The bounds of arguments in subroutines `TruncateCStates` and `TruncateCandNStates` 
are not getting checked when threading is on for c13 and c14. 
Removing `#ifndef _OPENMP` was causing problems since c13 and c14 are not always allocated. 
@billsacks  suggested using a similar method that is used for handling water isotopes here.
Based on this method the isotopes (i.e. c13 and c14) are being handled separately from the bulk and in another subroutine. Here we use `TruncateAdditional` for c13 and c14 only when they are allocated ( `if (use_c13)` or ` if (use_c14)`). 
Contributors other than yourself, if any: @billsacks
CTSM Issues Fixed (include github issue #):  #811 
Any User Interface …
> Resolve Issue #811: Bounds assertion for ciso when threading is on

- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/SnowHydrologyMod.F90
- src/utils/NumericsMod.F90
- src/utils/test/numerics_test/test_truncate_small_values.pf
The tolerance of 1.e-13 was occasionally exceeded. Although I haven't
done a careful analysis, it seems okay to me to increase this tolerance
slightly. See ESCOMP/ctsm#988 for details.
- Resolves ESCOMP/ctsm#988
Are answers expected to change (and if so in what way)? Possibly roundoff-level changes
Testing performed, if any: None yet
> Increase tolerance on near-zero truncation in UpdateState_TopLayerFluxes

- .gitignore
From
https://github.com/github/gitignore/blob/master/Global/Vim.gitignore
Motivated by the fact that a .swp file appeared in a PR. We probably
don't need all of these, but it looks like they should be safe to
include (i.e., I can't imagine a real file having a name like one of
these patterns, given that most of them begin with '.' or '_').
Testing performed, if any: none
> Add a bunch of ignore patterns for vim

- .zenodo.json
- README.md
- Add zenodo metadata file so that the Zenodo authorship is given simply as "CTSM Development Team", rather than trying to harvest authorship information from the list of git contributors.
- Document primary CTSM code management team members in the README
- Convert README to markdown, because I find it a little easier to work with than restructuredText. (Other than the addition of the CTSM code management team and fixing a link, content is the same as before.)
- Resolves #1005 
Testing performed, if any: None
> Document authorship and CTSM code management team

- cime_config/testdefs/ExpectedTestFails.xml
- tools/mksurfdata_map/src/mksurfdat.F90
Set harvest-related values to 0 rather than spval when running mksurfdata_map with all_veg = true (for smallville, etc.).
Compared with the baseline, this changes the following fields on the smallville surface dataset, which are all now 0 rather than spval:
```
RMS CONST_HARVEST_VH1                1.0000E+36            NORMALIZED  2.0000E+00
RMS CONST_HARVEST_VH2                1.0000E+36            NORMALIZED  2.0000E+00
RMS CONST_HARVEST_SH1                1.0000E+36            NORMALIZED  2.0000E+00
RMS CONST_HARVEST_SH2                1.0000E+36            NORMALIZED  2.0000E+00
RMS CONST_HARVEST_SH3                1.0000E+36            NORMALIZED  2.0000E+00
RMS CONST_GRAZING                    1.0000E+36            NORMALIZED  2.0000E+00
RMS CONST_FERTNITRO_CFT …
```
> Fix harvest-related values on surface datasets for smallville and other cases with all_veg

- Externals_CLM.cfg
This PR is created in response to the merge of PR #985 (and it's concurrent FATES PR).  The `Externals_CLM.cfg` file has been updated to point to the correct tag `sci.1.36.0_api.11.2.0`.
CTSM Issues Fixed (include github issue #): N/A
Testing performed, if any: None as deemed not necessary
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**
> Updating pointer to new fates tag for fixed biogeography update

- src/biogeophys/UrbBuildTempOleson2015Mod.F90
There is an implicit assumption in the urban building energy model that building width equals street width. However, this assumption has been relaxed and building width is now derived from the morphology dataset.
There is an implicit assumption in the urban building energy model that building width equals street width. However, this assumption has been relaxed and building width is now derived from the Jackson morphology dataset. Specifically, the equations which use H/Ws (building height over street width) now use H/Wb (building height over building width). Building width is derived from (Ws*froof)/(1-froof), where froof is the roof (building) fraction.
A simulation with the new equations indicate that as expected, for froof=0.5, answers are identical (because H/Ws = H/Wb). Differences …
> Building energy fix (issue #803).

- Externals.cfg
- Externals_cime.cfg
- bld/unit_testers/build-namelist_test.pl
- cime_config/config_compsets.xml
- cime_config/config_pes.xml
- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testmods_dirs/clm/waccmx_offline/shell_commands
- doc/ChangeLog
- doc/ChangeSum
Get reasonable PE layouts for the new FV3/SE grids.
Update cism external
Update cime external
Change single point tests to use stub ROF
Change tests to use gx1v7 rather than gx1v6
Update waccmx_offline to use START=1979
Fixes #1108
Fixes #1098
Fixes #1105
Fixes #1103
Fixes #1113
Are answers expected to change (and if so in what way)? No (other than waccmx_offline test)
Testing performed, if any: regular
> Adjust FV3/SE PE layouts

- Externals.cfg
- Externals_cime.cfg
- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/unit_testers/build-namelist_test.pl
- bld/unit_testers/xFail/expectedFail.pm
- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/PhotosynthesisMod.F90
Update cime so that default end year for GSWP3 forcing is 2013 because 2014 data is bad. Also update
the prevyr default for vcmax/jmax to what it was before ctsm1.0.dev102.
Fix some issues for finding initial condition files for Clm45 compsets. Also bring in updated CDEPS/CMEPS 
as they were required with the cime update.
Contributors other than yourself, if any: @wwieder 
CTSM Issues Fixed (include github issue #): #1107 
Fixes #1107 
Fixes #1067
Fixes #1121
Are answers expected to change (and if so in what way)? Yes
2010 and SSP compsets may change because of end year
Clm50 compsets with cold starts may change answers because of prevyr change (both Sp and Bgc)
Testing performed, if any: Ran a few tests, will run …
> Update cime so default end year for GSWP3 forcing is 2013 and change prevyr default for vcmax/jmax

- python/ctsm/run_sys_tests.py
I sometimes find myself wanting to check what options I provided to run_sys_tests after the fact. This change records this information in the SRCROOT_GIT_STATUS file. I admit that it's not obvious from the file name that this is the place to look for this information, but it seemed silly to create a second file just for this purpose, especially because there are some complexities in creating this file (in case you are rerunning in an existing directory). If people prefer, we could change the name of this file to something else.
@ekluzek @negin513 @slevisconsulting I wanted to point this out to you. Feel free to comment, but don't feel a need to. I'll merge directly to master unless any of you object.
> Record run_sys_tests command-line

- tools/contrib/singlept
Updates sources of surfacedata and land use time series in tools/contrib
updates source of data used by singlept script in tools/contrib directory.  
Not sure if we should also point to newer:
- datm forcing /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.GSWP3.0.5d.v1.1.c181207
-surface data /glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/release-clm5.0*
NA
Not sure how much these files with code modificatons?
NA
NA
created new surface dataset for single point simulation
> updates to current surfdata & landuse files in tools/contrib

- tools/mksurfdata_map/README.developers
- tools/mksurfdata_map/src/mksurfdat.F90
I think this may be important to avoid errors and/or wrong behavior in
some edge cases where we have < 0.5% cover of glacier and/or lake, and
other cases.
See https://github.com/ESCOMP/CTSM/issues/1118 for detailed thoughts
Resolves #1118 
Are answers expected to change (and if so in what way)? Possible answer changes, but this should be rare
Any User Interface Changes (namelist or namelist defaults changes)? N
I created a subset of our standard surface datasets with `make -f Makefile.data global-present` before and after this change. The three surface datasets created in this way (f09, f19 and f10) were all bit-for-bit. There could be answer changes in rare cases, but this …
> Move mksurfdata_map rounding of special landunits to before wetland fill

- python/ctsm/lilac_build_ctsm.py
Add --project argument to LILAC's create_newcase command
This isn't needed by anything in the LILAC workflow, but cime requires it on machines that expect PROJECT to be set. I guess that, until now, everyone who was testing and using the LILAC workflow had PROJECT set in their environment, or a .cesm_proj file in their home directory. @glemieux ran into this issue, however, and it would likely affect others.
- python testing (on my mac)
- LILACSMOKE_Vnuopc_D_Ld2.f10_f10_musgs.I2000Ctsm50NwpSpAsRsGs.cheyenne_intel.clm-lilac
In my view, that …
> Add --project argument to LILAC's create_newcase command

- cime_config/SystemTests/lilacsmoke.py
In LILACSMOKE test: Call case.load_env() before building the atm driver. This is needed for the atm driver build to use the correct module environment.
Things were working for me, and apparently for @ekluzek and @negin513 , without this change. But this is probably because our default module environment was similar to cime's cheyenne_intel environment. @glemieux was running into trouble because he has intel17 loaded in his default environment (whereas the environment loaded by cime uses intel19). This should fix that issue.
Are answers expected to change (and if so in what way)? Answers *may* change for the LILACSMOKE test, if baselines were generated with a slightly different compiler version …
> LILACSMOKE: Call case.load_env() before building the atm driver

- src/biogeochem/CNFireBaseMod.F90
- src/biogeochem/CNFireLi2014Mod.F90
- src/biogeochem/CNFireLi2016Mod.F90
- src/biogeochem/CNVegetationFacade.F90
- src/biogeophys/CanopyFluxesMod.F90
- src/biogeophys/EnergyFluxType.F90
- src/biogeophys/SoilMoistStressMod.F90
- src/main/FireDataBaseType.F90
- src/main/FireMethodType.F90
- src/main/clm_driver.F90
- src/utils/clmfates_interfaceMod.F90
Move btran2 so it's just inside of CNFire
Contributors other than yourself, if any: self
Fixes #1144
Currently just running the test: SMS_D_Ld3.f10_f10_musgs.I1850Clm50BgcCrop.cheyenne_intel.clm-default
Test builds and runs
> Have a copy of btran2 that's just inside CNFire

- src/biogeophys/BareGroundFluxesMod.F90
- src/biogeophys/CanopyFluxesMod.F90
- src/biogeophys/LakeFluxesMod.F90
- src/biogeophys/QSatMod.F90
- src/biogeophys/SurfaceHumidityMod.F90
- src/biogeophys/UrbanFluxesMod.F90
- src/biogeophys/test/HumanStress_test/test_humanstress.pf
- src/main/atm2lndMod.F90
Make most QSat output arguments optional
This has two benefits:
(1) It prevents callers from needing to create dummy variables to hold
outputs that they don't actually need.
(2) If neither qsdT nor esdT are needed, then we can avoid doing some
expensive calculations.
This is partly for the benefit of #1086 
- `SMS_D_Ld1_P4x1.f10_f10_musgs.I2000Clm50BgcCropQianRsGs.bishorn_gnu.clm-default` with comparison against master (bfb)
- `PFS_Ld20.f09_g17.I2000Clm50BgcCrop.cheyenne_intel` underway to look at performance changes, if any
> Make most QSat output arguments optional

- src/biogeochem/CNPhenologyMod.F90
Contributors other than yourself, if any:  billsacks
CTSM Issues Fixed (include github issue #): 1163.
The following tests were bfb with ctsm5.1.dev003:
ERP_D_Ld5.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-allActive
ERS_D_Ld6.f10_f10_musgs.I1850Clm45BgcCrop.cheyenne_intel.clm-clm50CMIP6frc
ERS_Ly5_P144x1.f10_f10_musgs.IHistClm51BgcCropGs.cheyenne_intel.clm-cropMonthOutput
> Fix issue#1163

- bld/namelist_files/namelist_defaults_ctsm.xml
- doc/ChangeLog
- doc/ChangeSum
Turn dribble_crophrv_xsmrpool_2atm when crop is on for clm4_5, clm5_0, and clm5_1 physics
Fix the finidat files being selected for 2000_control conditions for clm5_1
Contributors other than yourself, if any: self
Fixes #1158 
Another issue in #1166
Are answers expected to change (and if so in what way)? Yes (for all crop compsets and 2000Clm51 compsets)
Any User Interface Changes (namelist or namelist defaults changes)? N
Testing performed, if any: ran build-namelist unit tester, now running regular test suite
> Two answer changes turn dribble_crophrv_xsmrpool_2atm and correct clm5_1 finidat file for 2000 conditions

- src/biogeophys/CanopyStateType.F90
- src/biogeophys/PhotosynthesisMod.F90
- src/biogeophys/SoilWaterPlantSinkMod.F90
- src/biogeophys/WaterFluxBulkType.F90
Adding four new history fields relevant to plant hydraulic processes:
- QHR (patch-level hydraulic redistribution)
- VEGWPLN (local noon vegetation water potential)
- VEGWPPD (predawn vegetation water potential)
- VPD_CAN: canopy vapor pressure deficit (functional input to Medlyn model)
1123
No.
No, except for the availability of new history fields.
--compset I2000Clm50Sp --res f09_g17_gl4
Ran a five-day global simulation to confirm that the new history fields were writing out as expected. Compared local noon and predawn vegwp to half-hourly vegwp (at one point) and found agreement between the …
> Hydraulic redistribution

- .zenodo.json
- README.md
**Same as #1006 but for the release branch**
- Add zenodo metadata file so that the Zenodo authorship is given simply as "CTSM Development Team", rather than trying to harvest authorship information from the list of git contributors.
- Document primary CTSM code management team members in the README
- Convert README to markdown, because I find it a little easier to work with than restructuredText. (Other than the addition of the CTSM code management team and fixing a link, content is the same as before.)
- Bring in a few other changes from the README file on master (making the README file on the release branch identical to that on master)
- Addresses #1005 for release branch
Are answers expected to …
> Document authorship and CTSM code management team, release branch

- Externals_CLM.cfg
- src/main/histFileMod.F90
- src/utils/clmfates_interfaceMod.F90
This PR makes the necessary interface changes to enable the creation of a new fates history output variable.  The corresponding fates-side PR is https://github.com/NGEET/fates/pull/712.
Contributors other than yourself, if any: @rgknox 
CTSM Issues Fixed (include github issue #): N/A
Any User Interface Changes (namelist or namelist defaults changes)? None
Testing performed, if any: TBD
**NOTE: Be …
> Add new FATES history output variable dimension for patch age x fuel size class

- bld/unit_testers/build-namelist_test.pl
- cime_config/config_compsets.xml
- cime_config/testdefs/testlist_clm.xml
- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/CanopyFluxesMod.F90
Some small changes that can change answers in preparation of bringing in the option for bio-mass heat storage. This only changes answers for some compilers. This brings in some new terms (currently set to zero) that will be in use for clm5_1 when bio-mass heat storage is turned on. The terms that change are identical to the BHS version with the exception that some variables have a "p" index in the full BHS version as they are array terms rather than the scalars they are in here.
The full BHS version is PR #1016
Contributors other than yourself, if any: @swensosc 
CTSM Issues Fixed (include github issue #): None
Are answers expected to change (and if so in what way)? Roundoff changes for some compilers
Some new compsets …
> Small answer changes in preparation for adding option for bio-mass heat storage

- cime_config/testdefs/testlist_clm.xml
- doc/.ChangeLog_template
Main change is to instruct removing lines that don't apply in most sections (as we agreed upon at yesterday's CTSM software meeting). I have also tweaked some clarifying text in some places, and moved the
"significant changes" section higher up.
Thanks to @negin513 for suggesting this a while ago... though we didn't go with the suggestion at the time, I have eventually come around :-)
I am attaching examples of fairly minimal ChangeLog entries with the old and new conventions.
[ChangeLog_demo_old.txt](https://github.com/ESCOMP/CTSM/files/5643363/ChangeLog_demo_old.txt)
[ChangeLog_demo_new.txt](https://github.com/ESCOMP/CTSM/files/5643364/ChangeLog_demo_new.txt)
@ekluzek @negin513 @slevisconsulting @danicalombardozzi @olyson - If you get a chance, I'd like sign-off from all of you that …
> Update ChangeLog template

- cime_config/config_compsets.xml
- cime_config/config_pes.xml
As of cism2_1_74, CISM1 is no longer supported, so we don't need to have
a PE layout section for it.
**This simple change can be combined with some other changes in some upcoming tag.**
Testing performed, if any: none yet
> Remove support for CISM1

- src/biogeochem/FireEmisFactorsMod.F90
- src/biogeochem/MEGANFactorsMod.F90
See #1270 for details
This should be folded into an upcoming tag.
- Resolves ESCOMP/CTSM#1270
Tested on my mac with test `SMS_D_Ld1_P4x1.f10_f10_musgs.I2000Clm50BgcCropQianRs.bishorn_gnu.clm-o3`. With gfortran10, this passes and is bit-for-bit with a test without these changes but instead with FFLAG `-fallow-invalid-boz` added.
> Fix non-standard hexadecimal constant

- src/biogeophys/CanopyFluxesMod.F90
- src/biogeophys/OzoneBaseMod.F90
- src/biogeophys/OzoneFactoryMod.F90
- src/biogeophys/OzoneMod.F90
- src/biogeophys/OzoneOffMod.F90
- src/main/clm_driver.F90
Restructure ozone code to better accommodate the new ozone parameterization in #1232 . The changes here were heavily inspired by @ziu1986 's changes in #1232. My main goal was to demonstrate how we can bring in a new ozone stress formulation using a select case statement rather than object-oriented polymorphism, because this will keep the code simpler. A significant side benefit of this restructure was to allow me to remove the ozone stress terms from the restart file.
Contributors other than yourself, if any: Heavily motivated by changes from @ziu1986 as well as conversations with @sunnivin
Testing performed, if …
> Restructure ozone code

- src/biogeophys/BareGroundFluxesMod.F90
- src/biogeophys/CanopyFluxesMod.F90
- src/biogeophys/HydrologyNoDrainageMod.F90
- src/biogeophys/SoilFluxesMod.F90
- src/biogeophys/SoilHydrologyMod.F90
Change limitation of top layer evaporation/sublimation.
Sublimation from top soil layer and evaporation/sublimation from top snow layer needs to be limited to ensure moisture states do not become negative. The original formulation did not always work, so we added a new limitation to SoilFluxesMod.
Resolves ESCOMP/CTSM#1253 …
> Evaporation limit

- python/ctsm/lilac_build_ctsm.py
- python/ctsm/lilac_download_input_data.py
- python/ctsm/lilac_make_runtime_inputs.py
- python/ctsm/machine.py
- python/ctsm/machine_defaults.py
- python/ctsm/run_sys_tests.py
- python/ctsm/test/test_unit_machine.py
- python/ctsm/test/test_unit_run_sys_tests.py
- python/ctsm/utils.py
Adds a `--retry` option to `run_sys_tests`, adds a mechanism to set a machine-dependent default value of this option, and sets the default to 1 for izumi. So, if you don't specify the `--retry` option to `run_sys_tests`, the `--retry` option to `create_test` will be set to 1 for izumi, 0 for cheyenne or other machines. You can override this with the `--retry` option to `run_sys_tests`. This value of this option is printed both to stdout and to the (increasingly poorly named) `SRCROOT_GIT_STATUS` file in your testroot directory.
The motivation for this change was: Recently, nearly all of my test runs on izumi have a few tests fail with system errors. It started getting annoying to need to rerun them (and wait for the reruns to complete, then check them) before making a tag. With this …
> run_sys_tests: add --retry option on izumi

- cime_config/testdefs/testlist_clm.xml
- src/biogeophys/BalanceCheckMod.F90
- src/biogeophys/WaterDiagnosticType.F90
With changes forthcoming in FATES PR: https://github.com/NGEET/fates/pull/727 
Note: **This need not be synchronized with FATES 727**.
Column-scale water balance checks with FATES-HYDRO are passing with consistency, including scenarios where plants are allowed to by dynamic (grow, recruit, die and non-mortal turnover).  However, we are still failing a grid-level mass balance check.
Fixes: #510 
See issue: #1314 
This PR is a temporary fix, that bypasses grid-scale water mass checks only for fates-hydro runs.  Since column level checks pass, the expectation is that there is a bug on the upscaling from column to grid that is presently unknown. However, this PR will allow hydro tests to pass which will prevent further regressions.
Note that column level plant stored water was also added to …
> Bypass grid-level water mass check when fates hydro is active

- .config_files.xml
Fix paths to xlnd and slnd in .config_files.xml
CTSM Issues Fixed (include github issue #): Fixes #1438
the list of common …
> fix paths to slnd and xlnd in config_files

- doc/source/tech_note/Hydrology/CLM50_Tech_Note_Hydrology.rst
- doc/source/tech_note/Photosynthesis/CLM50_Tech_Note_Photosynthesis.rst
Updates to photosynthesis chapter in technical note per discussion in #1398.
Correct some errors and clarify derivation of stomatal conductance quadratic equation for Medlyn method.
Contributors other than yourself, if any: @djk2120 @heraldn
CTSM Issues Fixed (include github issue #):  Documentation aspects of #1398
I did a local build on the documentation.
> Updates to Tech Note Photosynthesis chapter

- Externals.cfg
- cime_config/SystemTests/lilacsmoke.py
- cime_config/buildnml
- src/README.unit_testing
Remove reference to LND_DOMAIN_FILE and LND_DOMAIN_PATH for nuopc
**These changes are from @mvertens . This is essentially a duplicate of #1589 but with fixed git history.**
Using NUOPC, the only need for having the xml variables LND_DOMAIN_FILE and LND_DOMAIN_PATH was for the LILAC smoke test. This PR removes that dependency by hard-wiring the path to the domain file for the test itself in lilacsmoke.py.
When LILAC is used in an external model (e.g. WRF), users will have to manually add the correct fatmlnd_frc and fsurdat entries for their particular resolution, so this will not come from CIME anyway. 
Contributors other than yourself, if any: @mvertens 
CTSM Issues Fixed: None
Any User Interface Changes (namelist or namelist …
> Remove reference to LND_DOMAIN_FILE and LND_DOMAIN_PATH for nuopc cases

- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testmods_dirs/clm/gregorian_cropMonthOutput/include_user_mods
- cime_config/testdefs/testmods_dirs/clm/gregorian_cropMonthOutput/shell_commands
- src/biogeochem/CNAnnualUpdateMod.F90
- src/biogeochem/CNC14DecayMod.F90
- src/biogeochem/CNCIsoAtmTimeSeriesReadMod.F90
- src/biogeochem/CNFUNMod.F90
- src/biogeochem/CNFireBaseMod.F90
- src/biogeochem/CNFireLi2014Mod.F90
- src/biogeochem/CNFireLi2016Mod.F90
- src/biogeochem/CNFireLi2021Mod.F90
- src/biogeochem/CNGapMortalityMod.F90
- src/biogeochem/CNNDynamicsMod.F90
- src/biogeochem/CNPhenologyMod.F90
- src/biogeochem/ch4Mod.F90
- src/cpl/lilac/lnd_comp_esmf.F90
- src/cpl/mct/lnd_comp_mct.F90
- src/cpl/mct/ndepStreamMod.F90
- src/cpl/nuopc/lnd_comp_nuopc.F90
- src/cpl/share_esmf/ndepStreamMod.F90
- src/main/clm_initializeMod.F90
- src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
- src/unit_test_shr/unittestTimeManagerMod.F90
- src/utils/AnnualFluxDribbler.F90
- src/utils/clm_time_manager.F90
- src/utils/clmfates_interfaceMod.F90
- src/utils/test/clm_time_manager_test/test_clm_time_manager.pf
Fix get_curr_yearfrac and get_prev_yearfrac with Gregorian calendar.
Also add unit tests of get_prev_yearfrac with a Gregorian calendar.
Contributors other than yourself, if any: @olyson gets most of the credit here
- Resolves ESCOMP/CTSM#1590
Are answers expected to change (and if so in what way)? YES, but very limited: From a search through the code, I think this will only impact CNDV cases when run with the Gregorian calendar. (The changed code is also used by the AnnualFluxDribbler, but only to set some values in gridcell-level balance checks; this can cause a run failure as in #1590 but I don't think it will actually cause any answer changes. The changed code is also used for time-interpolated prescribed dynamic landuse …
> Fix get_curr_yearfrac and get_prev_yearfrac with Gregorian calendar

- src/biogeophys/HydrologyDrainageMod.F90
Remove code that subtracts surface irrigation flux from qflx_runoff_col.  This is a diagnostic change only.  
Only the QRUNOFF variable on the history file will change.
ERP_D_P36x2_Ld5.f10_f10_mg37 and …
> remove irrigation flux from HydrologyDrainageMod

- Externals.cfg
- Externals_CLM.cfg
- bld/namelist_files/namelist_defaults_ctsm.xml
- doc/ChangeLog
- doc/ChangeSum
Minor FATES API update to point to the latest fates parameter file.  This PR is associated with https://github.com/NGEET/fates/pull/831.  This parameter file update aligns the FATES PFT optical properties to the CLM PFT optical properties.
Contributors other than yourself, if any: 
CTSM Issues Fixed (include github issue #): 
Note, #1683 is now not an issue since cheyenne modules were changed
Are answers expected to change (and if so in what way)? Yes.  FATES only DIFFs due to updates to the PFT optical properties.
Testing performed, if any: regular
> FATES parameter file API update to align PFT optical properties to CLM

- bld/namelist_files/namelist_definition_drv_flds.xml
- cime_config/config_pes.xml
- cime_config/testdefs/testlist_clm.xml
This PR reduces the PE count for aux_clm tests so that all (I think) tests fit in 4 nodes or less. This should
both (1) reduce queue wait time for tests and (2) reduce aux_clm testing cost (since, for high resolution
tests, most time is spent in initialization, so having more PEs increases cost significantly without actually
making the tests run much, if any, faster). While doing this, I also noticed some tests that felt redundant or unnecessary, and I have removed those.
To facilitate these changes, I have introduced new "S" PE layouts for the f09, f19 and 0.125nldas2 resolutions. These layouts use 4 nodes (but with DATM on just 1 node, because it is slightly faster to run it on one node than four nodes). (I considered running DATM on its own node like we do for production PE layouts, …
> Use small PE counts for aux_clm tests and remove some redundant / unnecessary tests

- src/biogeochem/NutrientCompetitionCLM45defaultMod.F90
This makes the crop allocation code in
NutrientCompetitionCLM45defaultMod consistent with that in
NutrientCompetitionFlexibleCNMod. This will be helpful so that I can
extract these into a shared subroutine.
From a 5-year run of IHistClm45BgcCrop at f19_g17 resolution, it seems
like this won't change answers: whenever peaklai is 1 during the
grainfill period, aleaf is already exactly 1e-5. I don't understand why
this is always the case; maybe, in Clm45, if peaklai isn't reached
before grainfill then it is never reached that growing season? I have
come to suspect that the difference between Clm45 and Clm50 in this
respect may actually be due to whether you're running with FUN, since
running with FUN changes some relevant driver sequencing. So it's
possible that this would change answers for …
> For CLM45 apply peaklai to aleaf in grainfill

- Externals_CLM.cfg
- doc/ChangeLog
- doc/ChangeSum
- src/utils/clmfates_interfaceMod.F90
This PR lays groundwork for enabling FATES MIMICS coupling. The soil decomposition namelist setting (ie none, century or mimics) is passed to FATES. If MIMICS is designated, FATES will prep new boundary conditions for use in MIMICS. Currently, it is generating one new output boundary condition for litter quality, which is the lignan carbon over total nitrogen ratio in the litter flux.
This should be integrated prior to #1643
This is synchronized with FATES PR: https://github.com/NGEET/fates/pull/850
@slevisconsulting @ekluzek @wwieder 
CTSM Issues Fixed (include github issue #):  None, #1643 completes the work though
Are answers expected to change (and if so in what way)?  No, this will only enable future FATES-MIMICS tests, but won't change …
> FATES MIMICS coupling prep work

- doc/ChangeLog
- doc/ChangeSum
- python/ctsm/site_and_regional/single_point_case.py
- python/ctsm/test/test_unit_singlept_data_surfdata.py
Previously `subset_data` explicitly checked to make sure the user has chosen at least one of the following options:
1) dominant pft(s)    or 
2) --include-nonveg (overrides default setting non-veg units to 0%)
However, @adrifoster pointed out that this limits FATES users who would not want to set a dominant pft(s) and would also want all 100% vegetated at the single point. So I removed this capability. 
Contributors other than yourself, if any: @adrifoster 
CTSM Issues Fixed (include github issue #): #1707
> Removing checks for dompft and include-nonveg

- tools/site_and_regional/run_neon.py
This change explicitly sets the NetCDF PIO mode and the PIO_REARRANGER_LND mode. 
No
No
Tested simple ABBY runs on Cheyenne and AWS - both work.  (Previously, it would use the wrong PIO_REARRANGER_LND value on AWS, resulting in very slow writes or crashes.)
> Fixes to run_neon 

- Externals.cfg
`tools/mksurfdata_esmf/gen_mksurfdata_build.sh` was failing for me on izumi with this error:
```
COMPILER = intel, MPILIB = mvapich2, DEBUG = FALSE, OS = LINUX
The PIO directory for the PIO build is required and was not set in the configure
Make sure a PIO build is provided for intel with mvapich2 in config_machines
```
Next `./manage_externals/checkout_externals` was giving a permission error because I don't have ssh keys set up on github.
Changing repo_url from git@... to https:... for ccs_config eliminates the need for the ssh keys.
@ekluzek 
Didn't open a corresponding issue.
No.
Any User Interface Changes (namelist or namelist defaults …
> Change repo_url from git@... to https:... for ccs_config

- tools/site_and_regional/modify_singlept_site_neon.py
Quick PR to fix #1752 (`./modify_singlept_site_neon.py`). This basically updates the links in this script to use the recent end points. 
Contributors other than yourself, if any: Thanks to @ekluzek for reporting this issue
CTSM Issues Fixed (include github issue #): 
Fixes #1752
Are answers expected to change (and if so in what way)? NA
Any User Interface Changes (namelist or namelist defaults changes)? NA
1. Tested it for all neon sites using `./neon_surf_wrapper.py`
./neon_surf_wrapper.py automatically subsets the data for all neon sites using `subset_data` and modify them using `./modify_singlept_site_neon.py`. 
2. Tested it for one neon site (BART) manually and it is working:
```
./modify_singlept_site_neon.py --neon_site BART --surf_dir …
```
>  PR to fix #1752: issue with listing file in ./modify_singlept_site_neon.py 

- python/ctsm/path_utils.py
Correct CIME path in ctsm 
CTSM Issues Fixed (include github issue 
Fixes #1749 -- fixes path
> correct the path to cime python code

- src/biogeophys/SoilHydrologyMod.F90
Modifying the calculation of the frost table and perched water table layers.
* PerchedWaterTable
1) Frost table depth
a) original frost table determination looped from the top 
of the soil column downward to the index of the first layer 
whose temperature was <= freezing, and whose neighbor above 
had a temperature above freezing.  The frost table depth is 
then given by the node of that soil layer, i.e. z(k_frz).  
b) in the new method, the same index is found, but the 
depth of the frost table is given by the depth of the top 
of the frozen layer, i.e. zi(k_frz-1).  Note zi(k_frz) would 
be the bottom of layer k_frz.  
2) Perched water table depth
a) in the original formulation, a loop from k_frz to layer 1 
was used to identify the deepest layer in 1:k_frz whose 
volumetric soil …
> correct perched water table calculation

- src/main/accumulMod.F90
This doesn't need to be on the restart file, and having it read from the
restart file causes wrong behavior when changing the model time step.
See https://github.com/ESCOMP/CTSM/issues/1789 for details
Resolves ESCOMP/CTSM#1789
Are answers expected to change (and if so in what way)? YES - for any case where the time step differs from the one originally used to create the initial conditions file. This typically means changing answers for any case with a time step other than 1/2 hour.
Testing performed, if any: None yet; about to run test suite
> Remove accumulation fields' PERIOD from the restart file

- python/ctsm/mksurfdata_download_input_data.py
- tools/mksurfdata_esmf/gen_mksurfdata_jobscript_single.py
- tools/mksurfdata_esmf/gen_mksurfdata_namelist.py
If mesh_file contains mesh_nx mesh_ny info, read it from the file.
Else abort and require user to enter it at the command line.
Confirm that the product of mesh_nx x mesh_ny (user-entered or from mesh_file) = elementCount (from mesh_file).
Address #1791 here, so as to name fsurdat files by their site/grid name rather than by their NX x NY.
Also address #1776 here, so as to stop hardwiring the mpirun command according to --machine in gen_mksurfdata_jobscript_single.py. Now get the mpirun command from env_mach_specific.xml.
Contributors other than yourself, if any: @ekluzek 
CTSM Issues Fixed (include github issue #): #1790 #1791 #1776 
Are answers expected to change (and if so in what way)? No.
Any User Interface Changes (namelist or namelist defaults changes)? No.
Testing performed, if …
> Add consistency checks for mesh_nx mesh_ny relative to mesh_file in gen_mksurfdata_namelist.py

- doc/source/users_guide/running-special-cases/Spinning-up-the-biogeochemistry-BGC-spinup.rst
Some minor corrections to instructions for spinning up CTSM. Branched from `ctsm5.1.dev092`.
**Contributors other than yourself, if any:** None.
**CTSM Issues Fixed:** n/a
**Are answers expected to change (and if so in what way)?** No.
**Any User Interface Changes (namelist or namelist defaults changes)?** No.
I have a 2-degree (f19_g17) spinup going now on Cheyenne, and it's successfully running the second part.
> Docs: Corrections to spinup instructions

- Externals.cfg
- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_drydep.xml
- bld/namelist_files/namelist_definition_drv_flds.xml
- src/biogeochem/DryDepVelocity.F90
- src/cpl/mct/clm_cpl_indices.F90
- src/cpl/mct/lnd_import_export.F90
- src/cpl/nuopc/lnd_import_export.F90
- src/main/clm_driver.F90
- src/main/clm_initializeMod.F90
- src/main/controlMod.F90
- src/main/lnd2atmMod.F90
- src/main/lnd2atmType.F90
Use `shr_drydep_mod` rather than the `seq_drydep_mod` module (which is merely a wrapper to shr_drydep_mod).
Namelist option `drydep_method` is removed.  The other dry deposition options were obsolete and were removed from the code base.  The only method available now is the "land" method.  We are dependent on the land model to provide deposition velocities of chemical constituents over land in all configurations.
CTSM Issues Fixed (include github issue #): #1822
Expect bit-for-bit unchanged
Namelist option `drydep_method` is removed
Only tested a few F compsets with chemistry
**NOTE: Be sure to …
> Switch to shr_drydep_mod module

- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/namelist_files/namelist_defaults_ctsm_tools.xml
- src/biogeophys/test/Photosynthesis_test/test_Photosynthesis.pf
- src/main/clm_initializeMod.F90
- src/main/clm_varpar.F90
- src/main/initVerticalMod.F90
- src/main/surfrdMod.F90
- tools/mksurfdata_esmf/README
- tools/mksurfdata_esmf/gen_mksurfdata_jobscript_multi.py
- tools/mksurfdata_esmf/gen_mksurfdata_namelist.py
- tools/mksurfdata_esmf/gen_mksurfdata_namelist.xml
Implementation of GaoOneill raw urban datasets and OlesonFeddema urban properties into mksurfdata_esmf.
1a. Incorporate new raw urban surface datasets for 1850, present day (2000, 2005), historical, and five SSPs (SSP1, SSP2, SSP3, SSP4, SSP5) developed primarily by @keerzhang1 from Gao and O'Neill (2021) and Gao and Pesaresi (2022). The urban properties (morphological, radiative, and thermal) in these datasets are described in Oleson and Feddema (2020). These datasets have PCT_URBAN calculated with respect to the total area of the gridcell (as discussed in #1716 ).  Note that the SSP1 datasets have been assigned to SSP1-1.9 and SSP1-2.6 and SSP4 datasets have been assigned to SSP4-3.4 and SSP4-6.0.
1b. A new building temperature stream file is implemented. The values of maximum interior …
> Implement GaoOneill raw urban datasets and OlesonFeddema urban properties into mksurfdata_esmf.

- src/main/histFileMod.F90
- tools/mksurfdata_esmf/src/mkfileMod.F90
- tools/mksurfdata_esmf/src/mksurfdata.F90
Simple mods to reduce confusion as explained in #1703 
CTSM Issues Fixed:
Fixes #1703 
No but pftmask and PFTDATA_MASK will not appear in history and fsurdat files, respectively.
Testing:
Confirmed that fsurdat files do not include PFTDATA_MASK and have no other changes.
> Remove pftmask from history and PFTDATA_MASK from fsurdat files

- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/namelist_files/namelist_definition_ctsm.xml
- src/main/clm_varctl.F90
- src/main/controlMod.F90
- src/main/surfrdMod.F90
- src/main/surfrdUtilsMod.F90
- tools/mksurfdata_esmf/src/mksoilcolMod.F90
- tools/mksurfdata_esmf/src/mksoiltexMod.F90
- tools/mksurfdata_esmf/src/mksurfdata.F90
This PR adds a new namelist option, "convert_ocean_to_land", which converts all wetland area to natural veg (typically bare ground) at runtime. This is set to true by default when using CLM51 physics.
In addition, this PR makes a minor change to the setting of soil properties in mksurfdata: Previously, soil properties were set to some default value outside of the pctlnd_pft-determined land mask. But I can't see any reason why that needs to be done, and doing so could remove some valid soil properties in the situation where there is a grid cell that has valid soil properties even though the pctpft dataset claims the area is ocean.
Note that this PR is into the ctsm5.2.mksurfdata branch. Most of the changes could be applied directly to master, but there are some related changes to …
> Add option to convert wetlands to land; apply it by default for CLM51 physics

- src/biogeophys/SurfaceAlbedoType.F90
Fix value of albgrd_col in SurfaceAlbefdoType.F90.
Previously, the wrong value (albgri_col) was being set in InitHistory.
Fixes #1788
Just for testing, I activated ALBGRD in hist_addfld2d to output the var and tested for SMS_Ld1_PS.f09_g17.I2000Clm50BgcCru.cheyenne_gnu.clm-datm_bias_correct_cruv7.
The tests passed on cheyenne.
> Fix albgrd_col value in SurfaceAlbedoType

- src/biogeochem/CNProductsMod.F90
Add error checking in ParitionWoodFluxes
Fixes #1263 
[WIP] tested with run_sys_tests against ctsm5.1-dev103
> Add error checking in ParitionWoodFluxes

- doc/design/surface_dataset_areas.rst
- tools/mksurfdata_esmf/src/mkVICparamsMod.F90
- tools/mksurfdata_esmf/src/mkesmfMod.F90
- tools/mksurfdata_esmf/src/mkfileMod.F90
- tools/mksurfdata_esmf/src/mkgdpMod.F90
- tools/mksurfdata_esmf/src/mkglacierregionMod.F90
- tools/mksurfdata_esmf/src/mkglcmecMod.F90
- tools/mksurfdata_esmf/src/mkharvestMod.F90
- tools/mksurfdata_esmf/src/mklaiMod.F90
- tools/mksurfdata_esmf/src/mklanwatMod.F90
- tools/mksurfdata_esmf/src/mkpeatMod.F90
- tools/mksurfdata_esmf/src/mkpftMod.F90
- tools/mksurfdata_esmf/src/mksoildepthMod.F90
- tools/mksurfdata_esmf/src/mksoilfmaxMod.F90
- tools/mksurfdata_esmf/src/mksurfdata.F90
- tools/mksurfdata_esmf/src/mkurbanparMod.F90
- tools/mksurfdata_esmf/src/mkvocefMod.F90
This PR reworks the mapping of landunit areas and the determination of wetland areas according to the plan laid out in #1716. (Note that the final implementation differs from the initial comment in #1716, as discussed in follow-up comments in that issue.) See the discussion there as well as the design document in this PR for details.
Contributors other than yourself, if any: Various discussions with others, especially @ekluzek and @slevisconsulting 
- Resolves #1716 
- Resolves #1930 
Are answers expected to change (and if so in what way)? Areas will change on surface datasets
(1) Compared 1850 f09 surface dataset before and after these changes (and …
> mksurfdata: Rework mapping of landunits to handle coastal areas more rigorously

- src/biogeophys/SoilFluxesMod.F90
Occasionally, h2osoi_ice was going significantly negative in UpdateState_TopLayerFluxes - see
https://github.com/ESCOMP/CTSM/issues/1979. As noted in that issue, this seems to be due to h2osoi_ice having a very different magnitude from h2osoi_liq, leading to greater-than-roundoff-level differences from zero final state in a relative sense (i.e., relative to the magnitude of h2osoi_ice) - I think because of the appearance of the sum (h2osoi_ice + h2osoi_liq) in the equations that limit fluxes.
To try to deal with this, I have reworked the handling of the evaporation constraint to directly limit both the liqevap and solidevap, so that both of them should result in the equivalent liq or ice states going to 0 within roundoff.
To do that, I needed to move the partitioning of the total flux …
> Rework handling of evaporation constraint in SoilFluxes

- cime_config/testdefs/testmods_dirs/clm/Fates/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/FatesColdAllVars/user_nl_clm
- cime_config/usermods_dirs/fates_sp/user_nl_clm
- doc/ChangeLog
- doc/ChangeSum
The current fates regression tests default to single precision.  This PR updates to double precision
The PR resolves #1986 
@ekluzek 
Yes …
> Update fates history tests to use double precision

- src/main/histFileMod.F90
Add more documentation to history tape code
* Add more breadcrumbs between related variables and methods
* Put related namelist flags/methods together
* Update some out of date comments
Doc-only change.
CTSM Issues Fixed (include github issue #):  none fixed, but preparation for fixing issue 27.
Ran unit tests to confirm new comments didn't break compilation
> Add more documentation to history tape code

- tools/site_and_regional/run_neon.py
Some small changes for quality of life improvements for the `run_neon` script.
1. fixed a couple lines so that python will stop complaining about deprecated things
2. added print statements about warning messages being not an issue, and that building/running may take a while
3. added a "success" print statement - **I'm not sure this will actually only print if "successful"**
@ekluzek is there a way to get a return value from case.submit that tells you if it actually submitted?
@ekluzek @TeaganKing @wwieder 
CTSM Issues Fixed (include github issue #): 
Are answers expected to change (and if so in what way)? No changes
only affects `run_neon`
> small changes to fix warnings; add print statements for clarity to users

- src/main/histFileMod.F90
List which variables are set.
Testing performed, if any: none
the list of common problems to …
> Document side effects of htapes_fieldlist() method

- bld/namelist_files/namelist_defaults_ctsm.xml
- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testmods_dirs/clm/FatesColdLandUse/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/collapse_pfts_78_to_16_decStart_f10/README
- cime_config/testdefs/testmods_dirs/clm/collapse_pfts_78_to_16_decStart_f10/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/f09_dec1990Start_GU_LULCC/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/mimicsFatesCold/README
- cime_config/testdefs/testmods_dirs/clm/mimicsFatesCold/shell_commands
- python/ctsm/modify_input_files/modify_fsurdat.py
- python/ctsm/test/test_sys_fsurdat_modifier.py
- python/ctsm/test/testinputs/default_data.cfg
- python/ctsm/test/testinputs/modify_fsurdat_short.cfg
- src/biogeochem/CropType.F90
- tools/mksurfdata_esmf/README
- tools/mksurfdata_esmf/gen_mksurfdata_jobscript_multi.py
Large changes to `namelist_defaults_ctsm.xml`.
Changes to various other files, mainly for consistency.
Attribution of work:
The original modifications to `namelist_defaults_ctsm.xml` related to the development of the new mksurfdata_esmf tool were done by @mvertens, as was the original development of the new mksurfdata_esmf tool itself.
Contributors other than yourself, if any: 
@ekluzek @mvertens 
Yes, because we are generating new fsurdat and landuse files.
Large changes to `namelist_defaults_ctsm.xml`.
- mksurfdata_esmf has been working to generate new fsurdat and landuse files.
- My branch's …
> Preparing alpha-ctsm5.2.mksrf.16_ctsm5.1.dev123 tag

- Externals.cfg
- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testlist_clm_nuopc.xml
- doc/ChangeSum
- doc/release-cesm2.2.ChangeLog
- src/main/histFileMod.F90
optimize history write
Same as #2114
Testing performed, if any: None, but normal testing will be done
> history write optimization

- cime_config/SystemTests/systemtest_utils.py
Issue #2109: For tests that invoke `cmds_to_setup_conda()`, manually calling the script invoking that function (e.g., `case.build` for `FSURDATMODIFYCTSM`) could fail if doing so with a conda environment already activated. The problem is that
```bash
conda run -n ctsm_pylib ...
```
seems to not actually use ctsm_pylib if, for instance the conda base environment is active. 
Issue #2111: For some users, FSURDATMODIFYCTSM is failing because conda doesn't load.
Putting `CONDA_PREFIX=;` before the `conda run` command fixes #2109.
Remaining tasks:
Contributors other than yourself, if any: @adrifoster, @ekluzek 
CTSM Issues Fixed:
- Fixes #2109
Testing performed, if …
> Improve robustness of run_python_script()

- src/biogeochem/CNPhenologyMod.F90
- src/utils/clm_time_manager.F90
- src/utils/test/clm_time_manager_test/test_clm_time_manager.pf
This PR adds a function, `is_doy_in_interval()`, that checks whether a given date (in day-of-year, DOY, format) is inclusive-within an interval given by start and end dates (also DOY).
This is in preparation for upcoming work on crop calendars.
I considered doing something fancier, using the ESMF date/time types, but eventually decided to just replicate the existing behavior of `CropPhenology()`. Specifically, there's no special consideration of leap days. This has two effects:
1. Intervals that include a leap day end, in leap years, on the calendar day before they end in non-leap years.
2. Intervals that occur entirely after a leap day are, in leap years, shifted one calendar day earlier than they occur in non-leap years.
I don't think this behavior is necessarily a bug, anyway. …
> Add is_doy_in_interval() function

- doc/source/tech_note/Fluxes/CLM50_Tech_Note_Fluxes.rst
- doc/source/tech_note/Lake/CLM50_Tech_Note_Lake.rst
- doc/source/tech_note/References/CLM50_Tech_Note_References.rst
Update documentation for Meier et al. (2022) roughness length parameterization
Fluxes, Lakes, and References chapters updated.
I believe I've fixed the CRLF problem created by my windows machine.  These are now line feeds (LF) as they are in unix systems and the repository.  I've built the documentation and pushed it to gh-pages and it looks fine.
Contributors other than yourself, if any:  @slevis-lmwg 
CTSM Issues Fixed (include github issue #):  Partial #2113
> Update to documentation for Meier et al. (2022) roughness length parameterization

- src/cpl/nuopc/lnd_import_export.F90
Remove the depricated shr_mpi_mod from this module and replace with ESMF_VMBroadcast.  …
> remove deprecated shr_mpi from this module

- src/biogeochem/CNPhenologyMod.F90
This PR rearranges the calculation of how much leaf and livestem C and N goes to biofuels vs. litter, in anticipation of me adding crop residue removal. This PR also makes the affected subroutine easier to read.
Specifically, this PR introduces four new variables in `CNOffsetLitterfall()`:
- `leafc_remaining`
- `leafn_remaining`
- `livestemc_remaining`
- `livestemn_remaining`
Those variables are initialized with the pool remaining after biofuel harvest. When I introduce crop residue removal, it will be able to act on (and update) those variables directly.
**Contributors other than yourself, if any:** @billsacks, @ekluzek 
**CTSM Issues Fixed:** None
**Are answers expected to change (and if so in what way)?** Yes, but only roundoff-level due to order-of-operations changes.
**Any User …
> Rearrange calculation of leaf/livestem C and N to biofuels/litter

- src/cpl/share_esmf/cropcalStreamMod.F90
Fixes a compiler error (for GNU 13.2) within cropcalStreamMod
Simple fix was to change whole-array assignments/references for the `starts` and `ends` arrays to specifically reference bounds (`begp` and `endp`).
Contributors other than yourself, if any: @billsacks 
CTSM Issues Fixed (include github issue #): Closes #2232
Successfully compiles with GNU 13.2
> cropcalStreamMod compiler error bug fix

- tools/contrib/ssp_anomaly_forcing_smooth
Refactors `ssp_anomaly_forcing` script to make it easier to read and more amenable to future development.
I originally started this in an attempt to resolve this script "stalling out" for me, but was unsuccessful—see #2181, which I'm now closing. I didn't want that work to go to waste, though, so I figured I would finish the refactor and submit that.
**Contributors other than yourself, if any:** @wwieder 
**Are answers expected to change (and if so in what way)?** Adds attributes to `write_climo` files' dimension variables.
**Any User Interface Changes (namelist or namelist defaults changes)?**
- Adds `--output-dir` option. Default `./anomaly_forcing` reproduces previous behavior.
- Makes synonyms for options with hyphens replacing …
> refactor ssp_anomaly_forcing

- src/biogeochem/CNVegCarbonFluxType.F90
- src/biogeochem/CropType.F90
Adds the following fields to restart files:
- `repr_grainc_to_seed_perharv_patch`
- `swindow_starts_thisyr_patch`
- `swindow_ends_thisyr_patch`
This resolves a failure in `COMPARE_base_rest` for one aux_clm test.
**CTSM Issues Fixed (include github issue #):**
- Fixes #2236
**Are answers expected to change (and if so in what way)?** Yes, but seemingly just for Smallville "no initial" restarts. Specifically, aux_clm test `ERS_Lm20_Mmpi-serial.1x1_smallvilleIA.I2000Clm50BgcCropQianRs.izumi_gnu.clm-cropMonthlyNoinitial`.
> Add sowing window fields and per-harvest grainC_to_seed to restart

- bld/namelist_files/namelist_defaults_ctsm.xml
- doc/ChangeLog
- doc/ChangeSum
ctsm5.1.dev155 had turned on Meier2022 surface roughness calculation by default for 5.1 compsets. Several bugs (#2238, #2264) have recently emerged that were not caught by pre-merge testing, so this tag reverts that change. Thus, the ZengWang2007 method is default for all compsets again.
**Are answers expected to change (and if so in what way)?** Yes, for 5.1 compsets.
**Any User Interface Changes (namelist or namelist defaults changes)?** 5.1 compsets now use ZengWang2007 roughness calculation method instead of Meier2022.
**Testing performed, if any:** aux_clm shows differences only in tests with 5.1 compsets.
> Do not use Meier roughness by default, even with 5.1.

- Externals.cfg
- doc/ChangeLog
- doc/ChangeSum
Update Externals.cfg to version from CESM3_dev aba49b6.
Contributors other than yourself, if any: @ekluzek 
- Resolves #2217
Are answers expected to change (and if so in what way)? No.
Any User Interface Changes (namelist or namelist defaults changes)? No.
Testing performed, if any: With this change, my tillage & residue branch works on Derecho.
> Update Externals.cfg to work on Derecho

- src/biogeochem/CNVegCarbonStateType.F90
This pull request proposes to fix two issues, #2216 , where the restarts for totvegc_13, totvegc_col_13, totvegc_14, totvegc_col_14 are never called because they are contained within a carbon_type = 'c12' if statement in CNVegCarbonStateType.F90, and #2119 , where we decided to not support initializing an isotope run with an initial file without isotope variables on it and instead have the model throw an error if the user attempts to do so.
The first issue, #2216, is fixed by rearranging the if statements in CNVegCarbonStateType.F90 so that the restarts are actually called for the totvegc isotope variables.
The second issue, #2119, is fixed by following the example given in subroutine check_interp_non_ciso_to_ciso within initInterp.F90.  That particular subroutine checks to see if c13 …
> Fix misplaced if statement and end model run if no-isotope to isotope run with user_init_interp=.false.

- src/biogeophys/LakeHydrologyMod.F90
Adds comment in `LakeHydrology()` pointing to issue #2227. This is an issue related to potentially too-high snow depth values that has been encountered in ELM but seemingly not in CTSM, so we're not actually implementing a possible fix—yet.
Contributors other than yourself, if any: @quantheory
- Closes #2227 (wontfix)
**Are answers expected to change (and if so in what way)?** No.
**Any User Interface Changes (namelist or namelist defaults changes)?** No.
**Testing performed, if any:** None
> Add comment in LakeHydrology() pointing to issue #2227

- python/ctsm/site_and_regional/run_neon.py
Moved `from ctsm import add_cime_to_path` up a few lines so that importing CIME now works
Contributors other than yourself, if any: @ekluzek @wwieder 
CTSM Issues Fixed (include github issue #): Fixes #2266
./run_neon works now
> Fix run_neon CIME path import

- src/biogeophys/BiogeophysPreFluxCalcsMod.F90
For tiny htop, remove endrun and add z0m = 0 and displa = 0.
Fixes #2264 
No, in the test-suites.
In longer simulation, prevents failure.
No.
The fix works. Tried alternate suggestion that failed, as documented in #2264.
> Remove endrun for Meier2022 case to work

- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_ctsm.xml
- cime_config/testdefs/ExpectedTestFails.xml
- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/UrbBuildTempOleson2015Mod.F90
Answer-changing merge-tag:
- Turn Meier2022 on for ctsm5.1. Had turned off temporarily while fixing a bug.
- Bring in Urban answer fix #2212.
- Turn tillage and residue removal on for ctsm5.1. Decisions posted below.
@olyson @samsrabin 
Fixes #2212 
Yes, for ctsm5.1 cases by making Meier2022 on, tillage low, and residue removal 0.5 by default.
Yes, for clm45/clm50 by including the #2212 fix.
Making Meier2022 the default for ctsm5.1 again.
Making tillage low by default for ctsm5.1.
Making residue removal 0.5 by default for ctsm5.1.
> Merge tag: Turn on meier2022 and bring in #2212

- .github/workflows/assign-to-project.yml
Adds a Github action to automatically assign high-priority items to [Project 25: High priority](https://github.com/ESCOMP/CTSM/projects/25).
CTSM Issues Fixed (include github issue #): None
Testing performed, if any: Doesn't seem to be working at the moment, but maybe that's just because it needs to be merged to the master branch.
> Automatically assign high priority items to project 25.

- cime_config/testdefs/testlist_clm.xml
Because unit testing doesn't work yet on Derecho (see #2329), this PR adds a new test to aux_clm that does unit testing on Izumi.
CTSM Issues Fixed (include github issue #): None
Testing performed, if any: None
> Add Izumi version of the aux_clm unit testing

- .github/workflows/assign-to-project.yml
Removes backticks from the YAML file that were causing syntax errors
**Contributors other than yourself, if any:** @mvdebolskiy, @ekluzek 
**Testing performed, if any:** None
> Fix "Assign to project" action (?)

- python/Makefile
Ensures that all steps of `make all` are run, even if pylint isn't clean.
**CTSM Issues Fixed (include github issue #):**
- Fixes #2316 
**Testing performed, if any:** `make all` now reaches "Successfully ran all standard tests" even though pylint isn't clean.
> Do not crash "make all" even if pylint isn't clean

- cime_config/testdefs/testlist_clm.xml
FSURDATMODIFYCTSM test (in aux_clm and clm_pymods) changed from `cheyenne_intel` to `derecho_gnu`. (Derecho Intel doesn't work with debug mode, which might be important for this test.)
**CTSM Issues Fixed (include github issue #):**
- Resolves #2362
- `FSURDATMODIFYCTSM_D_Mmpi-serial_Ld1.5x5_amazon.I2000Clm50SpRs.derecho_gnu` test passes
> Move FSURDATMODIFYCTSM test to Derecho

- doc/ChangeLog
- doc/ChangeSum
- src/biogeophys/CanopyFluxesMod.F90
- src/biogeophys/TemperatureType.F90
#2366 removes an instance of negative snocan in CanopyFluxesMod.F90 to resolve a test failure. Issue #2366 points out that snocan appears negative elsewhere, as well, and that possibly this is ok.
@billsacks 
Fixes #2366
Yes and let's see in what way.
No.
#2366 shows the LWISO test passing when not permitting negative snocan.
Next I will submit the test-suites.
> Merge-tag to resolve issue #2366

- src/main/histFileMod.F90
Change units on vector history fields for hillslope variables
no
no
the list of common …
> fix units for vector hh output

- cime_config/usermods_dirs/NEON/defaults/user_nl_clm
Put fsurdat back in 
`/cime_config/usermods_dirs/NEON/defaults/user_nl_clm`
to avoid setup error due to missing fsurdat in 
`SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm51Bgc.izumi_nag.clm-NEON-MOAB--clm-PRISM`
@wwieder 
No issue opened.
No.
The same test now passes.
> One-line fix for izumi NEON-MOAB test error introduced in #2472

- Externals_CLM.cfg
- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/unit_testers/build-namelist_test.pl
- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
- doc/ChangeLog
- doc/ChangeSum
Merging master back into b4b-dev after merging b4b-dev into master.
> Merge master into b4b-dev 2024-05-02

- src/biogeochem/CNDVType.F90
- src/biogeochem/CropType.F90
- src/biogeophys/EnergyFluxType.F90
- src/biogeophys/TemperatureType.F90
- src/main/accumulMod.F90
- src/main/test/accumul_test/test_accumul.pf
There are three types of accumulators specified in `accumulMod`: `timeavg`, `runmean`, and `runaccum`. `timeavg` is reset (value set to 0) every N steps, where N is the length of the period over which the field is being averaged. `runaccum` can be reset "manually" whenever the value passed in to the "update" subroutine is -99999.
`runmean`, in contrast, has no way to reset. This ends up being a problem for me with the crop calendar work, so I wanted to add that ability.
This PR adds the ability for `runmean` to be manually reset. It does the same for `timeavg`, and it makes it so that `runaccum` doesn't use the -99999 method anymore. See Design Note below for more details.
**Contributors other than yourself, if any:** @ekluzek 
- Fixes #2584
**Are answers expected …
> Allow "manual" resets of all accumulator types

- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/namelist_files/namelist_definition_ctsm.xml
- src/biogeophys/SaturatedExcessRunoffMod.F90
- src/main/clm_varctl.F90
- src/main/controlMod.F90
Add a namelist variable to toggle fsat calculation for hillslope columns
the topmodel-based fsat surface runoff scheme is not appropriate for upland hillslope columns, so allow user to set upland hillslope column fsat values to zero
**Are answers expected to change (and if so in what way)?** yes, for hillslope cases; changing fsat will change surface runoff
**Any User Interface Changes (namelist or namelist defaults changes)?** New parameter `hillslope_fsat_equals_zero` (default true).
**Testing performed, if any:** `aux_clm` mostly okay compared to `tmp-240620.n02.ctsm5.2.007`. However, test …
> add hillslope_fsat_equals_zero

- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
Motivated by problems with the NIWO test in #640 (this [comment](https://github.com/ESCOMP/CTSM/pull/640#issuecomment-2143101361))
@wwieder recommended switching the NIWO test to HARV.
@ekluzek recommended opening a PR to give this change more visibility. I implemented the change in #640 as well.
@wwieder 
No, but one NIWO test has been changed to a HARV test.
I ran the tests
```
SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.derecho_gnu.clm-default--clm-NEON-HARV
SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Fates.derecho_intel.clm-FatesFireLightningPopDens--clm-NEON-FATES-NIWO
```
- the former to show that the new test passes
- the latter because this test does not …
> Change a NIWO test to HARV and update expected failures

- python/ctsm/machine_defaults.py
When calling `run_sys_tests` on Derecho, each `STDIN` process requests 128 CPUs on the main queue. This PR makes it so that, by default, a more reasonable number of CPUs is requested on the develop queue.
So far, I've only made that one change. I'm assuming we'll need to discuss whether 32 is the best choice, whether anything else should change, etc.
**Contributors other than yourself, if any:** @ekluzek 
`./run_sys_tests -t SMS_Ln9.ne3pg3_ne3pg3_mg37.I2000Clm50Sp.derecho_gnu.clm-clm50cam6LndTun …
> Change CTSM machine default for Derecho to develop queue w/ 16 cpus

- cime_config/config_component.xml
- cime_config/config_compsets.xml
- cime_config/testdefs/testlist_clm.xml
The relevant tests are
```
SMS_Lm1.f10_f10_mg37.I1850Clm50BgcCropCmip6waccm.derecho_gnu.clm-basic
ERS_Ly3.f10_f10_mg37.I1850Clm50BgcCropCmip6.derecho_intel.clm-basic
SMS_Ld2_D_PS.f09_g17.I1850Clm50BgcCropCmip6.derecho_intel.clm-basic_interp
```
- The tests work when we change them from Clm50 to Clm60. 
- This requires changes to some associated hardwired stuff in /cime_config.
- We also want to update cmip6 references to cmip7  DROPPED THIS STEP
@ekluzek 
#2787 
No
No
No
Manual testing …
> Fix clm-basic tests

- cime_config/testdefs/testlist_clm.xml
Make this change to prevent failures reported in #2702.
Fixes #2702 
No.
No.
No.
None, yet.
> Change testlist_clm ne30pg3_t061 tests to ne30pg3_t232

- tools/mksurfdata_esmf/src/mkglcmecMod.F90
User found that the mksurfdata_esmf tool fails on a certain computer with this error:
`Program received signal SIGSEGV: Segmentation fault - invalid memory reference.`
and works when elevclass_o gets allocated before use in mkglcmecMod.F90.
Original post here:
https://bb.cgd.ucar.edu/cesm/threads/mksurfdata_esmf-done-around-glcmec.9624/post-57405
@olyson and @YuanSun-UoM
Resolves #2802 
No.
No.
No.
As posted in issue #2802, I'm testing on derecho...
PASS qsub …
> Remove unused variable elevclass_o in mkglcmecMod.F90

- src/biogeophys/EnergyFluxType.F90
Set eflx_building_lun to spval properly
Contributors other than yourself, if any: @cathyxinchangli 
CTSM Issues Fixed (include github issue #): #2793
Does this create a need to change or add documentation? Did you do so? No
Ran aux_clm.
Unexpected failures:
```
FAIL ERI_D.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningModeLDust COMPARE_base_hybrid
FAIL ERI_D.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningModeLDust COMPARE_base_rest
```
These failed because there was one variable not bfb, DPFCT_ROCK.
Unsure why that would be different.
> Set eflx_building_lun to spval properly

- bld/namelist_files/namelist_defaults_ctsm.xml
- doc/ChangeLog
- doc/ChangeSum
finidat updates needed for cesm's beta04 tag.
@ekluzek @olyson 
Relates to #2403 (I'm not confident that this fully resolves it though)
Yes, for clm6 ne30, f09, f19 cases, because pointing to new finidat files.
Updated namelist_defaults with new finidat files.
No but reminder to
izumi `./run_sys_tests -s aux_clm -c ctsm5.3.003 --skip-generate`
Compared to 003 because 004 was not available.
004 would differ from 003 only for the hillslope test, which is a clm6 test, so I expect it to …
> Clm60 finidat updates for ne30, f09, f19 grids

- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/unit_testers/build-namelist_test.pl
- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
CTSM PR for installing the POLARCAP grid in CESM.
All I did is replicate all the entries for ```ARCTICGRIS``` in namelist_defaults_ctsm.xml, which has year 1850, 2000, 1979-2026 support. It also has support for 6 combinations of atm/lnd physics (clm50, clm51, clm60) x (CAM6; CAM7). @ekluzek @samsrabin as the ```POLARCAP``` grid is new to CESM, I don't know that we need to support these older versions of atm/lnd physics, but I'm not necessarily opposed to them either. I'm flexible and will just defer to yall.
Surface datasets were generated with tag ```ctsm5.2.005```.
Fixes #2386  
Are answers expected to change (and if so in what way)? Not unless you're running this new grid.
Any User Interface …
> add "polarcap" grid for cesm3 release

- bld/CLMBuildNamelist.pm
@samsrabin recommended mods in the issue #2801 to fix the test.
@samsrabin 
Fixes #2801 
No
No
No
./create_test SMS_Ld10_D_Mmpi-serial.CLM_USRDAT.I1PtClm60Bgc.derecho_intel.clm-NEON-MOAB--clm-PRISM
worked on derecho (the original test that was failing was an izumi test, but I was avoiding izumi due to flakiness)
> Improve CLMBuildNamelist ability to detect NEON runs

- cime_config/buildnml
- doc/source/users_guide/running-special-cases/Running-with-MOAR-data-as-atmospheric-forcing-to-spinup-the-model.rst
- doc/source/users_guide/running-special-cases/Running-with-anomaly-forcing.rst
- doc/source/users_guide/running-special-cases/Running-with-your-own-previous-simulation-as-atmospheric-forcing-to-spinup-the-model.rst
- doc/source/users_guide/setting-up-and-running-a-case/customizing-the-clm-configuration.rst
- src/main/clm_varctl.F90
- tools/contrib/run_clm_historical
- tools/contrib/run_clmtowers
As in title.
@samsrabin 
Fixes #2743 
No
Yes
> Remove/replace refs to DATM_C*_YR_* variables

- src/biogeophys/SurfaceAlbedoType.F90
- src/biogeophys/UrbanAlbedoMod.F90
Remove num_solar and implement coszen filters in UrbanAlbedoMod.F90.  Purpose is to fix the issue that albgrd and albgri history fields depend on decomposition, for urban points, and improve performance.
Contributors other than yourself, if any: @billsacks 
CTSM Issues Fixed (include github issue #): #17 and #747
Does this create a need to change or add documentation? Did you do so? No
aux_clm testing on Derecho indicates bfb with ctsm5.3.009
I haven't done any evaluation of anticipated performance improvements.
> Remove num_solar and implement coszen filters in UrbanAlbedoMod.F90

- python/ctsm/crop_calendars/cropcal_figs_module.py
- python/ctsm/crop_calendars/generate_gdds_functions.py
- python/ctsm/run_sys_tests.py
See title.
**CTSM Issues Fixed:** None
**Testing performed, if any:** Tried it with both `-v` and `--debug`; looks good.
```shell
./run_sys_tests -s fire --skip-compare --skip-generate -v --dry-run
```
```
...
INFO: Tests:
INFO:    SMS_D_Ld65.f10_f10_mg37.I2000Clm45BgcCropQianRs.derecho_intel.clm-FireLi2014Qian
INFO:    SMS_D_Ld65.f10_f10_mg37.I2000Clm50BgcCru.derecho_gnu.clm-FireLi2016Cru
INFO:    SMS_D_Ld65.f10_f10_mg37.I2000Clm60BgcCrop.derecho_intel.clm-FireLi2024CruJra
...
```
> run_sys_tests: Print test list in --verbose/--debug

- .gitmodules
- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/namelist_files/namelist_definition_ctsm.xml
- bld/unit_testers/build-namelist_test.pl
- cime_config/buildnml
- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testmods_dirs/clm/FatesColdST3/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/clm60_monthly_matrixcn_soilCN30/user_nl_clm
- doc/ChangeLog
- doc/ChangeSum
- doc/source/users_guide/running-special-cases/Running-with-MOAR-data-as-atmospheric-forcing-to-spinup-the-model.rst
- doc/source/users_guide/running-special-cases/Running-with-anomaly-forcing.rst
- doc/source/users_guide/running-special-cases/Running-with-your-own-previous-simulation-as-atmospheric-forcing-to-spinup-the-model.rst
- doc/source/users_guide/setting-up-and-running-a-case/customizing-the-clm-configuration.rst
- src/biogeochem/CNGapMortalityMod.F90
- src/biogeophys/CanopyHydrologyMod.F90
- src/biogeophys/LunaMod.F90
- src/biogeophys/SnowHydrologyMod.F90
- src/main/clm_varctl.F90
- src/main/controlMod.F90
- src/main/histFileMod.F90
- src/utils/clmfates_interfaceMod.F90
- tools/contrib/run_clm_historical
- tools/contrib/run_clmtowers
Update cleanup branch to ctsm5.3.012
Testing performed, if any: regular
> Update branch to latest master ctsm5.3.012

- .gitmodules
- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testmods_dirs/clm/clm50cam7LndTuningMode/user_nl_datm
- cime_config/testdefs/testmods_dirs/clm/clm60cam7LndTuningMode/user_nl_datm
- doc/ChangeLog
- doc/ChangeSum
Update CDEPS so that CPLHIST cases and test use the "cam7" mode for DATM nextsw_cday_calc. Also change testmods for cam7 tuning mode to use this as well.
Contributors other than yourself, if any: 
 @billsacks for the CMEPS update itself
Fixes #2897
Are answers expected to change (and if so in what way)? For cplhist tests and cam7 tests
New option in DATM
nextsw_cday_calc (can be cam6 or cam7)
Does this create a need to change or add documentation? Did you do so? No No
Testing performed, if any: Running regular testing
> Update cdeps with cam7 nextsw cday changes

- bld/namelist_files/namelist_defaults_ctsm.xml
- cime_config/testdefs/testlist_clm.xml
Same as title, plus bring back the corresponding tests in the ctsm_sci test-suite.
@ekluzek 
Resolves #2544 
No
Added clm5-cam6 init_interp_attributes to namelist_defaults_ctsm.xml
No
As posted in #2544 the next four tests PASS with this PR's code mods:
```
SMS_Ln9.ne0POLARCAPne30x4_ne0POLARCAPne30x4_mt12.IHistClm50Sp.derecho_intel.clm-clm50cam6LndTuningMode_1979Start--clm-nofireemis
SMS_Ln9.ne0CONUSne30x8_ne0CONUSne30x8_mt12.IHistClm50Sp.derecho_intel.clm-clm50cam6LndTuningMode_2013Star …
```
> Bring back clm5-cam6 init_interp_attributes for ne0CONUS grid

- src/biogeochem/CNFUNMod.F90
Same as #2925 but into b4b-dev to make this bug-fix available immediately.
> Bug fix for izumi nag tests to pass (PR into b4b-dev)

- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testmods_dirs/clm/flexCN_FUN_BNF/include_user_mods
- cime_config/testdefs/testmods_dirs/clm/flexCN_FUN_BNF/user_nl_clm
- doc/ChangeLog
- doc/ChangeSum
- src/biogeochem/CNFUNMod.F90
Allocation statements should have been (0:mxpft) instead of (mxpft).
I introduced the bug in a small refactor requested in #2917.
Fixes #2924 
Not relative to ctsm5.3.016.
```
PASS SMS_D_Ld65.f10_f10_mg37.I2000Clm60BgcCrop.izumi_nag.clm-FireLi2024GSWP
PASS SMS_D.f10_f10_mg37.I2000Clm60BgcCrop.izumi_nag.clm-crop
PASS ERP_D_Ld5_P48x1.f10_f10_mg37.I1850Clm60Bgc.izumi_nag.clm-ciso
```
I will submit aux_clm next.
> Bug fix for izumi nag tests to pass (PR into tmp-241219)

- .gitmodules
- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/namelist_files/namelist_definition_ctsm.xml
- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testmods_dirs/clm/FatesColdHydro/shell_commands
- cime_config/testdefs/testmods_dirs/clm/FatesColdHydro/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/ciso_cwd_hr/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/clm60_monthly_matrixcn_soilCN30/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/flexCN_FUN_BNF/include_user_mods
- cime_config/testdefs/testmods_dirs/clm/flexCN_FUN_BNF/user_nl_clm
- doc/ChangeLog
- doc/ChangeSum
- src/biogeochem/CNFUNMod.F90
- src/main/controlMod.F90
Includes three tmp-241219 tags:
- tmp-241219.n01.ctsm5.3.016 Merge b4b-dev:
nfix_method options Houlton (default), Bytnerowicz (option)
- tmp-241219.n02.ctsm5.3.016 FATES hydro test update
- tmp-241219.n03.ctsm5.3.016 Bug fix for izumi nag tests to pass (b4b unless using Bytnerowicz)
@glemieux 
Fixes #2924 Fix problem with izumi nag tests
Fixes #2878 Remove fates_allom_smode shell_command update in FatesColdHydro testmod
Fixes #2869 Update temperature cost function for symbiotic nfix in FUN
Yes, fates cases only, as documented in the ChangeLog
nfix_method, as documented in the …
> Merge tmp-241219 branch to master

- WhatsNewInCTSM5.3.md
- Rearranging a bit to highlight things that users probably care about more than software engineers.
- Removing line breaks, as this harms searchability.
- Using hash marks as Markdown headers instead of title underlines, as these are easier to understand.
It might be easier for further discussion to take place in a Google Doc for now... I've made one [here](https://docs.google.com/document/d/12KS5eU6gIaicZ4hJhgZWmys8fLLl5IkxwC_Pi76FuHw/edit).
**Contributors other than yourself, if any:** @ekluzek 
**CTSM Issues Fixed:** None
**Testing performed, if any:** None needed.
> Update "What's New in CTSM 5.3"

- src/utils/clmfates_interfaceMod.F90
The flag that specifies using LUH datasets is passed earlier in the call sequence so that it can be used to guide memory allocations.  If landuse is turned on, particularly in fates nocomp mode, then the space required for patch allocations changes.  Therefore this flag has to be passed earlier, before these allocations are decided on.
This PR does not need to be synchronized with, but does need to precede: https://github.com/NGEET/fates/pull/1226
Contributors other than yourself, if any: @ckoven 
Are answers expected to change (and if so in what way)? none, b4b
Does this create a need to change or add documentation? Did you do so? no need
TBD, but …
> change the order of passing the "use_fates_luh" flag

- .gitmodules
- bld/namelist_files/namelist_defaults_ctsm.xml
- doc/ChangeLog
- doc/ChangeSum
This simple PR updates the default fates parameter file as well as the fates tag.
This parameter file should be coordinated with ngeet/fates#1334 fates pull request.
To do:
Testing performed, if any: regular fates
> ctsm5.3.025: Update default FATES parameter file to API 37.1

- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testmods_dirs/clm/Fates/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/FatesColdAllVars/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/FatesColdDryDepSatPhen/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/FatesColdHydro/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/FatesColdMeganSatPhen/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/FatesColdSatPhen/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/GddGen/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/fire_emis/user_nl_clm
- cime_config/testdefs/testmods_dirs/clm/glcMEC_long/user_nl_clm
- doc/ChangeLog
- doc/ChangeSum
- src/main/clm_initializeMod.F90
- src/utils/clmfates_interfaceMod.F90
In FATES branch runs, prevents attempts to re-allocate arrays that already are allocated (in the restart file). This prevents run failures. However, it exposes a failure in the `COMPARE_base_hybrid` step of ERI tests, due to a bad `hist_mfilt`; this is also fixed.
Remaining tasks:
Baseline comparisons may fail for the following testmods:
- `Fates`
- `FatesColdAllVars`
- `FatesColdDryDepSatPhen`
- `FatesColdHydro`
- `FatesColdMeganSatPhen`
- `FatesColdSatPhen`
- `fire_emis`
- `glcMEC_long`
However, this is only because I have changed `hist_mfilt` for those to 1. (From 365 for the `Fates` testmods; from 30 for `fire_emis`; from 12 for `glcMEC_long`). This ensures that the dates in the history filenames are the same for both parts of the ERI test.
When this is next in the merge queue:
1. …
> ctsm5.3.030: Fix FATES branch runs

- tools/contrib/README
- tools/contrib/SpinupStability_BGC_v11_SE.ncl
Add a spinup equilibrium script suitable for global ne30pg3 spectral element simulations to tools/contrib.
Contributors other than yourself, if any: @adamrher 
CTSM Issues Fixed (include github issue #):  #821
Are answers expected to change (and if so in what way)?  No
Does this create a need to change or add documentation? Did you do so?  No. No.
Validated on /glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM53_DEV/ctsm53n02ctsm52027_ne30pg3t232_AD/lnd/hist/
> Add Spectral Element grid equilibrium script to tools/contrib

- tools/mksurfdata_esmf/src/mkinputMod.F90
Adding a mksurfdata_esmf warning about the code automatically changing the order of user selected --model-mesh-nx, ny when the user has set nx to 1, because the code expects ny set to 1 instead.
Fixes #2847 
No
A warning in mksurfdata_esmf's .log output
No
Submitted mksurfdata_esmf both ways as documented in #2847 and got b4b same results. In the case that had to be reversed, the .log file included a warning explaining the situation.
> Avoid mksurfdata_esmf pitfall with --model-mesh-nx, ny

- src/CMakeLists.txt
With recent versions of CTSM, the unit test build wasn't working on my Mac, and @adrifoster was having the same problem. The problem was that the unit test build wasn't finding the esmf library. I don't understand how this was working on derecho; my best guess is that the modules are adding something needed to the link line that isn't added on a simpler system that doesn't use modules.
This PR explicitly finds ESMF and adds necessary includes and link line flags. This borrows from what's done for the share unit test build, though differs somewhat from that. This also removes some things that are unneeded. It also removes `shr_pio_mod.F90` from the unit test build. I believe that that change (credit to @adrifoster ) allows the unit test build to work in either of two configurations: either …
> Get pFUnit-based unit tests working on my Mac

- .gitignore
- python/ctsm/toolchain/gen_mksurfdata_jobscript_single.py
- tools/mksurfdata_esmf/Makefile
- tools/mksurfdata_esmf/src/mksoiltexMod.F90
Refactors `mksoiltex()` subroutine to make it easier to understand and avoid duplicated code.
Also:
- Checks for negative values in top sand layer (was already happening for other soil components)
- Changes `gen_mksurfdata_jobscript_single.py` to use user's `ACCOUNT` environment variable as default.
As of eacff1077:
- ~~f19 outputs are bit-for-bit identical with previous version (disabled organic_o option 2)~~ Removing that code
> mksurfdata_esmf: Refactor mksoiltex

- .github/workflows/docker-image-build-publish.yml
- .github/workflows/docker-image-build.yml
- .github/workflows/docker-image-common.yml
- .github/workflows/docker-image-get-version.yml
- doc/ctsm-docs_container/Dockerfile
- doc/ctsm-docs_container/README.md
- doc/ctsm-docs_container/get_version.sh
The GitHub workflow that builds and pushes new versions of the ctsm-docs container doesn't include a tag with the version number. This PR fixes that. It also checks that the included version tag is formatted correctly and hasn't been used before.
- Resolves #3126
**Does this create a need to change or add documentation? Did you do so?** Yes, the README.md file next to the Dockerfile; yes.
**Testing performed, if any:** Tested at https://github.com/samsrabin/test-CTSM-docs-version-tagging:
- [Works if Dockerfile has exactly one new …
> Fix ctsm-docs container version tagging

- .github/workflows/docs.yml
- doc/ChangeLog
Skip the docs.yml workflow if these are the only changed files in `doc/**`:
- `ChangeLog`
- `ChangeSum`
- `UpdateChangelog.pl`
**Testing performed, if any:** As desired, 1daa3b5 didn't trigger docs.yml.
> Don't build docs for ChangeLog/Sum

- .github/workflows/docker-image-build.yml
- .github/workflows/docker-image-common.yml
- Delete an unused and possibly bad output
- Try another way to get one image tag
- Resolved #3139
**Testing performed, if any:** Tested in a separate repository and it works!
> Fix error when docker-image-common.yml runs on new tag

- .github/workflows/docker-image-build.yml
- .github/workflows/docs-ctsm_pylib.yml
- .github/workflows/docs.yml
- .github/workflows/fleximod_test.yaml
- .github/workflows/formatting_python.yml
Some workflows currently run on the push of a new tag, even if there are no changes associated with the tag. This is duplicative, because the workflows will have already run before the tag was created (either due to `push:` or `pull_request:` conditions).
This workflow makes it so that the push of a new tag will not trigger workflows unless it comes with actual changes to files.
- Resolves #3142
**Testing performed, if any:** Tested in a separate repo and it seems to work as expected.
> Don't run workflows on plain tag creation

- .github/ISSUE_TEMPLATE/03_documentation.md
- .github/workflows/docker-image-common.yml
- .github/workflows/docs-build-and-deploy.yml
- .github/workflows/docs.yml
- .gitmodules
- doc/ChangeLog
- doc/ChangeSum
- doc/ctsm-docs_container/Dockerfile
- doc/source/users_guide/working-with-documentation/building-docs-multiple-versions.rst
- doc/source/users_guide/working-with-documentation/building-docs-prereqs-mac.md
- doc/source/users_guide/working-with-documentation/building-docs-prereqs-windows.md
- doc/source/users_guide/working-with-documentation/docs-intro-and-recommended.md
- doc/testing.sh
- Fixes Podman builds on Ubuntu (mostly; see ESMCI/doc-builder#27)
- Docker now preferred on non-Mac systems
- Improves docs docs
**Contributors other than yourself, if any:** @slevis-lmwg and @katierocci for Windows testing!
- Resolves #3163
**Does this create a need to change or add documentation? Did you do so?** Yes
**Testing performed, if any:** See checks on this PR.
> ctsm5.3.050: Doc infrastructure and docs: fixes and improvements

- .gitmodules
- cime_config/config_archive.xml
Update of ccs_config to the point where the new intel-oneapi compiler is used for derecho_intel which changes answers for derecho_intel.
Fixes #2476
Are answers expected to change (and if so in what way)? Yes, just for derecho_intel
Does this create a need to change or add documentation? Did you do so? No No
Testing performed, if any: will run regular testing
Right now just working on getting derecho_gnu to work for mpi-serial
> Bring in the answer changing (for derecho_intel) ccs_config update

- .github/workflows/docs-omnibus.yml
- .github/workflows/fleximod_test.yaml
- .gitmodules
- doc/ChangeLog
- doc/ChangeSum
- doc/testing.sh
As of ctsm5.3.051 (#3125), `bin/git-fleximod checkout -o` [results in an unclean state](https://github.com/ESCOMP/CTSM/issues/3210#issuecomment-2925808249), which [prevents the documentation from deploying](https://github.com/ESCOMP/CTSM/actions/runs/15365441594/job/43237738393). This PR resolves the issue. It also edits a couple of GitHub workflows to catch such problems in the future.
Additionally, ctsm5.3.051 did not bring in the version of CMEPS required for FTorch to build properly—see #3214. Fixing it is going to be a big task, so for now we're just removing it. Issue to add it back: #3228
- Resolves #3210
- Resolves #3214
**Any User Interface …
> ctsm5.3.055: Remove broken FTorch submodule

- cime_config/SystemTests/lreprstruct.py
Resolves https://github.com/ESCOMP/CTSM/issues/3313
The previous logic caused problems if "GRAIN" appeared in two (or more) strings, where one was a substring of the other. For example, in LREPRSTRUCT_Ly1_P128x1.f10_f10_mg37.I1850Clm50BgcCrop.derecho_gnu.clm-ciso--clm-cropMonthOutput, before this replacement, one line contained 'GRAINN_TO_FOOD' and a later line contained (among other things) "'GRAINN_TO_FOOD_PERHARV', 'GRAINN_TO_FOOD_ANN'". This was problematic because the first replacement of GRAINN_TO_FOOD incorrectly led to replacements in the later strings as well.
This new logic should solve this issue.
Resolves #3313  
Are answers expected to change (and if so in what way)? Possible field diffs for …
> Fix string replacements in lreprstruct test

- .gitmodules
- cime_config/SystemTests/rxcropmaturityinst.py
- cime_config/SystemTests/rxcropmaturityskipgeninst.py
- cime_config/config_archive.xml
- cime_config/config_tests.xml
- cime_config/testdefs/ExpectedTestFails.xml
- cime_config/testdefs/testlist_clm.xml
- cime_config/testdefs/testmods_dirs/clm/crop/user_nl_clm
- doc/ChangeLog
- doc/ChangeSum
- python/ctsm/crop_calendars/check_rxboth_run.py
- python/ctsm/crop_calendars/generate_gdds_functions.py
- src/main/histFileMod.F90
- tools/contrib/SpinupStability_BGC_v10.ncl
- tools/contrib/SpinupStability_BGC_v11_SE.ncl
- tools/contrib/SpinupStability_SP_v9.ncl
- tools/contrib/run_clm_historical
- tools/site_and_regional/neon_gcs_upload
> Merge ctsm5.3.063 into b4b-dev

- .github/workflows/check-clm6-aliases.yml
- .github/workflows/docker-image-build-publish.yml
- .github/workflows/docker-image-common.yml
- .github/workflows/docker-image-get-version.yml
- .github/workflows/docs-build-and-deploy.yml
- .github/workflows/docs-common.yml
- .github/workflows/docs-omnibus.yml
- .github/workflows/docs-update-ctsm_pylib.yml
- .github/workflows/docs-update-dependency-common.yml
- .github/workflows/docs-update-doc-builder.yml
- .github/workflows/docs.yml
- .github/workflows/python-tests.yml
- .github/workflows/xml-check.yml
- doc/ctsm-docs_container/Dockerfile
Changes to GitHub actions to improve security.
CTSM Issues Fixed:
- Resolves #3291
- Resolves #3342
**Does this create a need to change or add documentation? Did you do so?**
**Testing performed, if any:** Workflows on this PR.
> Harden GitHub actions

- bld/namelist_files/namelist_defaults_ctsm.xml
Updating namelist defaults with the most up-to-date ctsm54 fsurdat/landuse files (only ne30, f09, f19 resolutions) that I generated using branch tag `alpha-ctsm5.4.CMIP7.05.ctsm5.3.063`.
After merging this PR, I will make new tag `alpha-ctsm5.4.CMIP7.06.ctsm5.3.063`.
Fixes #3302 (last checkbox)
> Add ctsm54 ne30, f09, f19 fsurdat/landuse files to namelist defaults

- bld/namelist_files/namelist_defaults_ctsm.xml
Addresses this comment 
https://github.com/ESCOMP/CTSM/issues/2701#issuecomment-3089709273
Addresses in part #2701 
```
./create_newcase --case ~/cases_dev/test_hdm_clm45 --compset I1850Clm45Bgc --res f10_g37 --run-unsupported
./create_newcase --case ~/cases_dev/test_hdm_clm5 --compset I1850Clm50Bgc --res f10_g37 --run-unsupported
./create_newcase --case ~/cases_dev/test_hdm --compset I1850Clm60Bgc --res f10_g37 --run-unsupported
```
and
```
./case_setup
./preview_namelists
vi CaseDocs/lnd_in
```
Confirmed by inspection that the first two cases use the old hdm file and the third case uses the new hdm file.
> New hdm stream file should be used only with clm6 by default

- bld/namelist_files/namelist_defaults_ctsm.xml
- cime_config/testdefs/ExpectedTestFails.xml
Stop pointing to the modified finidat with suffix 64bitoffset. That finidat became unnecessary when #3132 got merged.
Resolves #3252 
See issue
> Fix failing LII2 tests in ctsm5.4 branch

- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/namelist_files/namelist_definition_ctsm.xml
- doc/ChangeLog
- doc/ChangeSum
- src/dyn_subgrid/dynSubgridControlMod.F90
- src/main/histFileMod.F90
merge ctsm5.3.065 to b4b-dev
Testing performed, if any: None
> Merge master 20250728

- .gitmodules
- cime_config/testdefs/testlist_clm.xml
Also adds `interim_restart` test suite with SMS, ERR, and IRT tests. Expected ERR and IRT to fail but only the latter does.
- Resolves #3356
- Resolves #3357 
- Resolves #3359
**Testing performed, if any:** New `interim_restart` test suite.
> Interim restart fix: Update CIME and CMEPS

- tools/contrib/abm_raw.ncl
- tools/contrib/popden.ncl
Two new ncl scripts for future reference.
@lifang0209 
Addresses part of #2701 
No
No
No
None
> Add abm and popden scripts to /tools/contrib

- doc/ChangeLog
- doc/ChangeSum
- doc/README.CHECKLIST.master_tags
Merging master (ctsm5.3.066) to b4b-dev.
> Merge master 20250808

- py_env_create
- python/ctsm/test/test_sys_py_env_create.py
- python/empty.yml
Changes to account for conda and mamba updates on Derecho.
- Resolves #3402
- Automatic unit/formatting checks on PR.
> Fix py_env_create and tests

- src/biogeochem/CNAllocationMod.F90
- src/biogeochem/CNC14DecayMod.F90
- src/biogeochem/CNCIsoFluxMod.F90
- src/biogeochem/CNCStateUpdate1Mod.F90
- src/biogeochem/CNFUNMod.F90
- src/biogeochem/CNFireEmissionsMod.F90
- src/biogeochem/CNGRespMod.F90
- src/biogeochem/CNGapMortalityMod.F90
- src/biogeochem/CNMRespMod.F90
- src/biogeochem/CNNStateUpdate1Mod.F90
- src/biogeochem/CNPhenologyMod.F90
- src/biogeochem/CNVegCarbonFluxType.F90
- src/biogeochem/CNVegCarbonStateType.F90
- src/biogeochem/CNVegMatrixMod.F90
- src/biogeochem/CNVegNitrogenStateType.F90
- src/biogeochem/CNVegStructUpdateMod.F90
- src/biogeochem/CropType.F90
- src/biogeochem/DryDepVelocity.F90
- src/biogeochem/NutrientCompetitionCLM45defaultMod.F90
- src/biogeochem/NutrientCompetitionFlexibleCNMod.F90
- src/biogeophys/PhotosynthesisMod.F90
- src/biogeophys/TemperatureType.F90
- src/cpl/share_esmf/cropcalStreamMod.F90
- src/main/filterMod.F90
- src/main/pftconMod.F90
- src/soilbiogeochem/TillageMod.F90
Making `npcropmin` and `npcropmax` private to `pftconMod` helps set up for adding an `is_prognostic_crop` parameter to the parameter file, contributing to #3388. Making these private required adding an `is_prognostic_crop()` function, the contents of which will eventually be replaced by a read of that new parameter.
- Contributes to #3388
> Make npcropmin/max private to pftconMod

- bld/CLMBuildNamelist.pm
- bld/namelist_files/namelist_defaults_ctsm.xml
- bld/unit_testers/build-namelist_test.pl
- doc/ChangeLog
- doc/ChangeSum
From https://github.com/NCAR/LMWG_dev/issues/116
to /glade/campaign/cesm/cesmdata/cseg/inputdata/lnd/clm2/paramdata/ctsm60_params_cal115_c250813.nc
this time staying closer to our naming conventions (unlike with the previous temporary paramfile).
Next I converted from netCDF-4 to cdf5 and ./rimport-ed the file:
```
nccopy -k cdf5 lnd/clm2/paramdata/ctsm60_params_cal115_c250813.nc lnd/clm2/paramdata/ctsm60_params_cal115_c250813_cdf5.nc
./rimport -file lnd/clm2/paramdata/ctsm60_params_cal115_c250813_cdf5.nc
```
@linniahawkins @wwieder 
Ctsm6 answers will change. …
> ctsm5.3.074: Update ctsm6 default paramfile and IC files
