ESCOMP/CTSM

README.rst

@ekluzek it would be good to have this in the release version. I think this can simply be merged to master. But I'm assigning you simply because I don't want to mess with any work you have going on.

Point to helpful wiki pages in the readme

---

bld/namelist_files/namelist_definition_clm4_5.xml

I changed this in the code a while ago, but never updated this
documentation

Fix documentation of where SMB is computed for vegetated columns

---

bld/unit_testers/xFail/expectedFail.pm
cime_config/config_component.xml

Fix typo in setting of LND_TUNING_MODE when coupled to CAM and make it consistent.
Fixes #294

Make LND_TUNING_MODE correct and consistent when coupled with CAM

---

src/biogeophys/HydrologyNoDrainageMod.F90
src/biogeophys/LakeHydrologyMod.F90
src/biogeophys/TemperatureType.F90
src/biogeophys/WaterStateType.F90

adding diagnostic variable SNOTXMASS for CMIP6
List of changes: 
- added SNOTXMASS 
- added SNOTXMASS_ICE (inactive)
- added SNOWICE_ICE (inactive)
- added SNOWLIQ_ICE (inactive)
- added c2l scale types for SNOWICE, SNOWLIQ
Example Python code that processes the new diagnostic variable to compute snow internal temperature can be found here:
https://github.com/lvankampenhout/Jupyter_notebooks/blob/master/Snow%20internal%20temperature%20in%20CLM.ipynb

Snow integrated temperature

---

cime_config/usermods_dirs/cmip6_output/user_nl_clm
doc/ChangeLog
doc/ChangeSum
src/biogeophys/BalanceCheckMod.F90
src/biogeophys/HydrologyNoDrainageMod.F90
src/biogeophys/LakeFluxesMod.F90
src/biogeophys/LakeHydrologyMod.F90
src/biogeophys/TemperatureType.F90
src/biogeophys/WaterStateType.F90
src/biogeophys/WaterfluxType.F90
src/main/TopoMod.F90
src/main/atm2lndType.F90

@ekluzek - I have reviewed @lvankampenhout 's changes (see #303). The rest of the changes here are pretty trivial, but I'm submitting them in case you want to review them.
Fixes #271

Add some land ice diagnostic variables needed for cmip6

---

cime_config/testdefs/testlist_clm.xml

Add tests for aux_cime_baselines from the most highly tested cases.
And add some edison tests for fates test list, again for the most highly tested cases

Add tests for aux_cime_baselines edison tests for fates

---

cime_config/config_compsets.xml

Based on direction from Dave Lawrence
@ekluzek @dlawrenncar can you review this to make sure I got this right? It's the same as what we came up with at yesterday's meeting, but it seems like it would be good to give it a final once-over.

Add science_support for more compsets

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README
README_EXTERNALS.rst

Templates for Pull Requests and issues, to make sure more information is given on each of those. Also an initial cut at a contributing document to outline expectations of how code changes come into CTSM. Please review and give feedback. But, since this is non-code, we can make changes at any time, so I'll probably bring it in before I get feedback from everyone.

Initial version of templates for contributing, PR's and issues

---

Externals_CLM.cfg

This is just an update of the tag for fates in externals.

Updated fates external tag

---

bld/namelist_files/namelist_defaults_clm4_5.xml

This PR updates the default fates parameter file for testing. This should be synced with FATES side updates to coastal grasses.
https://github.com/NGEET/fates/pull/435
Contributors other than yourself, if any:  @xuchongang  (fates side developments)
No 

fates parameter file for coastal grasses

---

tools/contrib/singlept

minor changes on instructions for users
NA
NA
NA
NA
(aux_clm on cheyenne for gnu/pgi and hobart for gnu/pgi/nag is the standard for tags on master)

minor changes to instructions and code

---

src/biogeochem/CNVegCarbonStateType.F90

See issue #608  for discussion of the original user-reported problem that generated this investigation and solution.
Allow for reseeding of generic crops and increase the totvegc threshold that triggers this from 0 to 1 gC/m2.
This is a work-around solution that addresses the issue of dead generic crops in an accelerated-mode BGC simulation initialized from our current BGC-Crop initial files.
A remaining problem not addressed by this request is that there are generic crops present in our surface datasets that are used by BGC-CROP simulations.  This is not desirable as all crops should be distributed among the prognostic crop types.  This issue will be addressed by either continued discussion in issue #608 or by opening another issue.
Contributors other than yourself, if any: D. Lawrence, …

Reseed generic crops and increase totvegc threshold from 0 to 1 (see issue #608)

---

src/main/controlMod.F90
src/main/histFileMod.F90

This is a thing that got fixed on CTSM master, but somehow those changes didn't make it to the fates_next_api branch.  I cherry-picked the two commits from https://github.com/ESCOMP/ctsm/pull/398 here.  I haven't tested yet.
re-fixes: #85

Re-fixing mfilt fix to the fates_next_api branch

---

src/cpl/nuopc/lnd_import_export.F90

Changes in nuopc cap to fix bugs found in testing

fixed bug on nuopc cap

---

tools/mksurfdata_map/README.developers

Testing performed, if any: none

Add list of checks that should be done when making new surface datasets

---

.github/PULL_REQUEST_TEMPLATE.md

Point to list of common problems in PR template

---

Externals_CLM.cfg
bld/namelist_files/namelist_defaults_clm4_5.xml

Update the default FATES parameter file.
See https://github.com/NGEET/fates/pull/659
Are answers expected to change (and if so in what way)? yes, see discussion in https://github.com/NGEET/fates/pull/659
Any User Interface Changes (namelist or namelist defaults changes)?  yes, default parameter file changed
see https://github.com/NGEET/fates/pull/659

Updating FATES default parameter file to api 11.1

---

doc/ChangeLog
doc/ChangeSum
src/biogeochem/ch4Mod.F90
src/cpl/mct/lnd_import_export.F90
src/cpl/nuopc/lnd_import_export.F90
src/main/clm_driver.F90
src/main/lnd2atmMod.F90
src/main/lnd2atmType.F90

Bracket the model time-step loop to calculate balance checks at the gridcell level, as explained in #315
Avoid duplication by using calculations from the column-level checks.
@billsacks 
CTSM Issues Fixed (include github issue #): #315 
No
No
The following tests PASS bit-for-bit against dev097:
ERI_D_Ld9.f10_f10_musgs.I1850Clm50Bgc.cheyenne_gnu.clm-default
ERP_D_Ld5.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-allActive
ERS_Ly3_Mmpi-serial.1x1_smallvilleIA.IHistClm50BgcCropQianGs.cheyenne_gnu.clm-cropMonthOutput
ERP_D.f10_f10_musgs.IHistClm50Bgc.cheyenne_gnu.clm-decStart

Gridcell-level error check for methane (CH4)

---

Externals_CLM.cfg
src/utils/clmfates_interfaceMod.F90

This adds the spitfire type definitions to the interface with FATES.  THis is needed so that we can remove a call inside FATES to CNFireFactoryMod.
This is synchronized with https://github.com/NGEET/fates/pull/676
Any User Interface Changes (namelist or namelist defaults changes)? no, user will not be aware of fix
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the …

fates-interface: added fixes to lightning interface

---

bld/namelist_files/namelist_defaults_ctsm.xml
doc/.ChangeLog_template
src/biogeochem/CNFireLi2021Mod.F90

A few fixes for CLM51 configurations: three for fire and one for the organic_frac_squared namelist default
- Resolves ESCOMP/CTSM#1171
- Partially addresses ESCOMP/CTSM#1169
- Partially addresses ESCOMP/CTSM#1166
Are answers expected to change (and if so in what way)? YES: significant answer changes for CLM51
Any User Interface Changes (namelist or namelist defaults changes)? fix namelist default for organic_frac_squared
Testing performed, if any: none yet

Clm51 fixes

---

src/biogeochem/CNFireLi2021Mod.F90

Resolves ESCOMP/CTSM#1173
Are answers expected to change (and if so in what way)? Yes, for CLM51 cases with BGC

Call correct routine to calculate btran2 for CNFireLi2021

---

src/biogeochem/CNVegetationFacade.F90
src/cpl/nuopc/lnd_comp_nuopc.F90
src/main/initSubgridMod.F90

Adds threading support for the CMEPS driver.  
aux_clm cheyenne intel comparing to ctsm5.1.dev030 baseline
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

threading for cmeps driver

---

src/cpl/lilac/lnd_comp_esmf.F90
src/cpl/lilac/lnd_import_export.F90
src/cpl/mct/lnd_comp_mct.F90
src/cpl/mct/lnd_import_export.F90
src/cpl/nuopc/lnd_comp_nuopc.F90
src/cpl/nuopc/lnd_import_export.F90
src/cpl/utils/lnd_import_export_utils.F90

This PR fixes the way the way co2 from the atm is handled in both the nuopc and mct caps.
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and …

bug fixes in for co2 in both nuopc and mct caps

---

src/biogeochem/CNPhenologyMod.F90

De-duplicated code in CropPhenology subroutine relating to planting of non-winter-cereal crops.
CTSM Issues Fixed (include github issue #): #1479 
Testing performed, if any: None

1479 crop sowing dedupe

---

doc/source/tech_note/Surface_Albedos/CLM50_Tech_Note_Surface_Albedos.rst

Change "min" to "max" in technical note Eq. 2.3.16
Contributors other than yourself, if any: robin-zweigel
CTSM Issues Fixed (include github issue #): #1566 

Fix errors in master technical note Eq. 2.3.16

---

doc/source/tech_note/Surface_Albedos/CLM50_Tech_Note_Surface_Albedos.rst

Change "min" to "max" in technical note Eq. 2.3.16
Contributors other than yourself, if any: robin-zweigel
CTSM Issues Fixed (include github issue #): #1566 

Fix errors in release technical note Eq. 2.3.16

---

tools/contrib/README
tools/contrib/SpinupStability_BGC_v10.ncl
tools/contrib/SpinupStability_SP_v9.ncl
tools/contrib/SpinupStability_v10.ncl

Update the BGC spinup stability script and add an SP spinup stability script.
CTSM Issues Fixed (include github issue #): #1132
Are answers expected to change (and if so in what way)?  Only for spinup stability script output
Ran scripts against existing data

Update spinup stability scripts

---

tools/mksurfdata_map/unit_testers/test_mkgridmapMod.F90
tools/mksurfdata_map/unit_testers/test_mkindexmapMod.F90
tools/mksurfdata_map/unit_testers/test_mksurfdata_map.F90

I included notes with the first commit to this PR, that list the mods necessary to fix the build errors.
@ekluzek 
Fixes #1575 
No
No
In `/glade/work/slevis/git/mksurfdata_maps_wo_src_masks/tools/mksurfdata_map/unit_testers` I type `gmake` and get no errors now

Correct build errors in mksurfdata tools testers

---

src/main/controlMod.F90

Same as #1214 from @sunnivin but for release branch
Contributors other than yourself, if any: @sunnivin
CTSM Issues Fixed (include github issue #): #1191 on the release branch
Are answers expected to change (and if so in what way)? Yes, when `hist_avgflag_pertape` is changed
Any User Interface Changes (namelist or namelist defaults changes)? N
Testing performed, if any: None yet

Fix issue 1191 on release branch

---

Externals.cfg
cime_config/config_component.xml
cime_config/testdefs/ExpectedTestFails.xml
doc/ChangeLog
doc/ChangeSum
tools/site_and_regional/run_neon.py

Minor changes to fix run_neon to handle the updated neon listing file ([listing.csv](https://neon-ncar.s3.data.neonscience.org/listing.csv)).
Contributors other than yourself, if any: N/A
CTSM Issues Fixed (include github issue #): Issue #1668
Any User Interface Changes (namelist or namelist defaults changes)? N/A
N/A

fixing run_neon for addition of v2

---

python/ctsm/test/test_sys_lilac_build_ctsm.py

Resolves ESCOMP/CTSM#1739
CTSM Issues Fixed (include github issue #): Resolves ESCOMP/CTSM#1739
Testing performed, if any: python testing

Workaround for some python system tests

---

doc/source/tech_note/Plant_Hydraulics/CLM50_Tech_Note_Plant_Hydraulics.rst

Fix issue #1864  in master documentation
Contributors other than yourself, if any: @swensosc 
CTSM Issues Fixed (include github issue #): #1864

Fix issue #1864 in master documentation

---

doc/source/tech_note/Plant_Hydraulics/CLM50_Tech_Note_Plant_Hydraulics.rst

Fix issue #1864 in CLM5 release documentation
Contributors other than yourself, if any: @swensosc 
CTSM Issues Fixed (include github issue #): #1864

Fix issue #1864 in release documentation

---

cime_config/SystemTests/fsurdatmodifyctsm.py
cime_config/SystemTests/funitctsm.py
cime_config/SystemTests/lciso.py
cime_config/SystemTests/lgrain2.py
cime_config/SystemTests/lii.py
cime_config/SystemTests/lii2finidatareas.py
cime_config/SystemTests/lilacsmoke.py
cime_config/SystemTests/lreprstruct.py
cime_config/SystemTests/lvg.py
cime_config/SystemTests/lwiso.py
cime_config/SystemTests/soilstructud.py
cime_config/SystemTests/ssp.py
cime_config/buildlib
cime_config/buildnml
python/Makefile

Black reformats buildlib and buildnml 
Are answers expected to change (and if so in what way)? NO
Any User Interface Changes (namelist or namelist defaults changes)? NO
the list of common problems to watch out …

black reformat python files for consistancy across cesm

---

doc/source/users_guide/testing/testing.rst

Fixes rendering and improves instructions in Build-namelist section of Testing chapter of User's Guide.
Contributors other than yourself, if any: @ekluzek 
CTSM Issues Fixed (include github issue #): **None**
Are answers expected to change (and if so in what way)? **No**
Any User Interface Changes (namelist or namelist defaults changes)? **No**
Testing performed, if any: **Built HTML locally.**

User's Guide, testing: Fix/fill Build-namelist section

---

doc/source/conf.py
doc/source/tech_note/Methane/CLM50_Tech_Note_Methane.rst
doc/source/users_guide/running-special-cases/Running-with-tillage.rst
doc/source/users_guide/running-special-cases/index.rst

Fixes a table in the Methane tech note, and updates instructions for changing tillage settings.
CTSM Issues Fixed (include github issue #): None
Testing performed, if any: Build works with both Docker method and VSCode.

Minor docs updates

---

src/biogeochem/CropType.F90

This is a one line change to reduce the length of a rather long string constant in this file and enable compiling with cray 17.0.0

fix for cray compiler format issue

---

py_env_create

Fix issues with py_env_create after derecho update 
**Contributors other than yourself, if any:**
@ekluzek identified the fix for this issue, I'm just opening the PR to address it.
**CTSM Issues Fixed (include github issue #):**
#2563
**Are answers expected to change (and if so in what way)?**
none

Fix py env create

---

src/biogeophys/SoilTemperatureMod.F90

Fix comments on urban thermal variables
Contributors other than yourself, if any:  Junjie Yu (University of Manchester)
CTSM Issues Fixed (include github issue #): #2763
Are answers expected to change (and if so in what way)?  No
Does this create a need to change or add documentation? Did you do so?  No
None, comments only.

Fix comments on urban thermal variables

---

cime_config/testdefs/ExpectedTestFails.xml
doc/ChangeLog
doc/ChangeSum

Merge master 2024 11 09

---

.gitmodules
bld/CLMBuildNamelist.pm
bld/unit_testers/build-namelist_test.pl
cime_config/testdefs/ExpectedTestFails.xml
cime_config/testdefs/testlist_clm.xml
cime_config/testdefs/testmods_dirs/clm/FatesColdST3/user_nl_clm
doc/ChangeLog
doc/ChangeSum
src/main/histFileMod.F90
src/utils/clmfates_interfaceMod.F90

Merge ctsm5.3.013 tag on main development into b4b-dev
Testing performed, if any: was done for the ctsm5.3.013 tag

Merge ctsm5.3.013 into b4b-dev

---

.gitmodules
cime_config/testdefs/ExpectedTestFails.xml
cime_config/testdefs/testlist_clm.xml
cime_config/testdefs/testmods_dirs/clm/FatesColdHydro/shell_commands
cime_config/testdefs/testmods_dirs/clm/FatesColdHydro/user_nl_clm
cime_config/testdefs/testmods_dirs/clm/flexCN_FUN_BNF/include_user_mods
cime_config/testdefs/testmods_dirs/clm/flexCN_FUN_BNF/user_nl_clm
doc/ChangeLog
doc/ChangeSum

Merge to ctsm5.3.017

---

.gitmodules
bld/namelist_files/namelist_defaults_ctsm.xml
doc/ChangeLog
doc/ChangeSum
src/biogeophys/SoilTemperatureMod.F90
src/biogeophys/UrbBuildTempOleson2015Mod.F90

Merge master ctsm5.3.026 to b4b-dev.

Merge master 20250227

---

tools/mksurfdata_esmf/gen_mksurfdata_namelist.xml

Correct urban mesh file for CMIP7 data

Correct urban Mesh file

---

.gitmodules
cime_config/config_archive.xml

Update externals to cesm3_0_alpha06c. Also bring in the revert for the st_archive issue.
Brings in the fix for #3198
Any User Interface Changes (namelist or namelist defaults changes)? No 
Does this create a need to change or add documentation? Did you do so? No
Testing performed, if any: regular ctsm_sci

Update externals to cesm3_0_alpha06c

---

doc/source/conf.py

@slevis-lmwg Please approve and merge this before merging b4b-dev!
**Are answers expected to change (and if so in what way)?** None
**Any User Interface Changes (namelist or namelist defaults changes)?** None
**Testing performed, if any:** It works now.

Fix a couple of things in documentation conf.py

---

doc/source/tech_note/Fluxes/CLM50_Tech_Note_Fluxes.rst

Fix equation number rendering (2.5.119)
Contributors other than yourself, if any: No
CTSM Issues Fixed:
- Resolves #3196 
Does this create a need to change or add documentation? Did you do so? No
Built documentation and verified fix.

Fix typo in Chapter 5 of technical note

---

doc/source/tech_note/Dust/CLM50_Tech_Note_Dust.rst
doc/source/tech_note/Ecosystem/CLM50_Tech_Note_Ecosystem.rst
doc/source/tech_note/Fluxes/CLM50_Tech_Note_Fluxes.rst
doc/source/tech_note/Lake/CLM50_Tech_Note_Lake.rst
doc/source/tech_note/Photosynthesis/CLM50_Tech_Note_Photosynthesis.rst

Fix rendering of asterisks in equation subscripts and superscripts.
**Are answers expected to change (and if so in what way)?** None
**Any User Interface Changes (namelist or namelist defaults changes)?** None
**Does this create a need to change or add documentation? Did you do so?** Yes?
**Testing performed, if any:** Local build.

Tech Note: Fix sub/superscript asterisks in equations

---

tools/mksurfdata_esmf/gen_mksurfdata_namelist.xml

Urban mesh was pointing to a 3x3min instead of a 0.25x0.25 file

---

.gitmodules

**CTSM Issues Fixed:** Resolves #3358.
**Testing performed, if any:** `interim_restart` test suite: All pass.

Update MOSART to mosart1.1.11
